class EasyQuestionRepository {
	public constructor() {
		
	}

	public getAll(): Question[]
	{
		return [
			new Question('I eat ____ cake.','a',['a','I','an']),
			new Question('I have a dog ____ a cat.','and',['and','on','old']),
			new Question('I throw ____ the rubbish.','away',['away','come','you']),
			new Question('I have a ____ dog.','big',['big','for','the']),
			new Question('The sky is ____.','blue',['blue','we','and']),
			new Question('I ____ read.','can',['can','not','red']),
			new Question('____ here.','Come',['Come','Where','Blue']),
			new Question('Please sit ____, Mary.','down',['down','up','play']),
			new Question('I can\'t ____ my ruler.','find',['find','one','funny']),
			new Question('This gift is ____ you.','for',['for','two','you']),
			new Question('The clown is ____.','funny',['funny','look','can']),
			new Question('I ____ to school by bus.','go',['go','you','little']),
			new Question('I ____ my mum make cookies.','help',['help','here','run']),
			new Question('Come ____.','here',['here','the','three']),
			new Question('____  eat a banana . ','I',['I','Down','Where']),
			new Question('The fox is ____ the box.','in',['in','and','it']),
			new Question('Tom ____ my friend.','is',['is','up','go']),
			new Question('We like ____.','it',['it','my','find']),
			new Question('They ____ into the water.','jump',['jump','can','make']),
			new Question('My ____ brother is cute.','little',['little','you','it']),
			new Question('____ at the bee.','Look',['Look','See','Away']),
			new Question('My mum will ____ a pie.','make',['make','yellow','look']),
			new Question('My mum will make a pie for ____.','me',['me','here','in']),
			new Question('Where is ____ pencil?','my',['my','see','not']),
			new Question('Tom does ____ go to school today.','not',['not','one','can']),
			new Question('I have ____ apple for lunch.','one',['one','play','a']),
			new Question('I ____ with Mary and Tom.','play',['play','red','down']),
			new Question('The apple is ____.','red',['red','make','my']),
			new Question('I ____ with my dog.','run',['run','red','said']),
			new Question('Come here, ____ Mary.','said',['said','funny','not']),
			new Question('I ____ with my eyes.','see',['see','three','and']),
			new Question('____ kitten is cute.','The',['The','You','Run']),
			new Question('I have ____ rabbits.','three',['three','where','jump']),
			new Question('We walk ____ the park.','to',['to','see','here']),
			new Question('I have ____ hands.','two',['two','help','a']),
			new Question('We run ____ to the hill.','up',['up','we','two']),
			new Question('____ are good friends.','We',['We','Run','The']),
			new Question('____ are you?','Where',['Where','Come','Little']),
			new Question('The lemon is ____.','yellow',['yellow','look','to']),
			new Question('How are ____?','you',['you','can','blue']),
			new Question('I did ____ my homework.','all',['all','soon','must']),
			new Question('I ____ a good student.','am',['am','there','she']),
			new Question('They ____ my good friends.','are',['are','at','this']),
			new Question('Look ____ the bee.','at',['at','what','yes']),
			new Question('She ____ an ice-cream yesterday.','ate',['ate','under','on']),
			new Question('I will ____ home soon.','be',['be','out','good']),
			new Question('I have ____ hair.','black',['black','want','but']),
			new Question('Mary has ____ eyes. ','brown',['brown','please','do']),
			new Question('I want to play ____ I can\'t.','but',['but','are','too']),
			new Question('Dad ____ home at 6 o’clock yesterday.','came',['came','that','black']),
			new Question('He ____ his homework.','did',['did','brown','but']),
			new Question('____ you like swimming?','Do',['Do','There','Yes']),
			new Question('I ____ an ice cream everyday.','eat',['eat','did','into']),
			new Question('There are ____ birds on the tree.','four',['four','ate','now']),
			new Question('I ____ a teddy bear on my birthday.','get',['get','this','well']),
			new Question('You did a ____ job!','good',['good','like','she']),
			new Question('I ____ a lovely cat.','have',['have','good','yes']),
			new Question('____ is my friend.','He',['He','Am','Have']),
			new Question('Come ____ the house.','into',['into','there','pretty']),
			new Question('I ____ my teacher.','like',['like','well','too']),
			new Question('You ____ do your homework now.','must',['must','brown','what']),
			new Question('I get a ____ toy on my birthday.','new',['new','but','all']),
			new Question('Do you like dogs? ____, I don\'t.','No',['No','This','Yes']),
			new Question('Can I eat that ____?','now',['now','no','came']),
			new Question('The ball is ____ the table.','on',['on','out','did']),
			new Question('____ family went hiking last Sunday.','Our',['Our','He','Say']),
			new Question('The fish jumps ____ of the tank.','out',['out','our','ate']),
			new Question('Can I eat that, ____?','please',['please','went','good']),
			new Question('My sister is ____. ','pretty',['pretty','she','yes']),
			new Question('My dog ____ away yesterday.','ran',['ran','will','ride']),
			new Question('I ____ a bike to school.','ride',['ride','four','into']),
			new Question('He ____ a ghost last night.','saw',['saw','under','new']),
			new Question('What did you ____?','say',['say','must','black']),
			new Question('____ is my sister.','She',['She','They','Like']),
			new Question('I am ____ hungry.','so',['so','well','at']),
			new Question('I will be back ____.','soon',['soon','this','into']),
			new Question('____ is my book.','That',['That','Too','Get']),
			new Question('____ are two cars on the road.','There',['There','Please','What']),
			new Question('____ go to school on foot.','They',['They','With','That']),
			new Question('____ is my friend, Jane.','This',['This','Soon','Ride']),
			new Question('I ride a bike to school. Me, ____.','too',['too','have','be']),
			new Question('The cat is ____ the table.','under',['under','white','like']),
			new Question('I ____ to play with Tom.','want',['want','who','must']),
			new Question('I ____ late for school yesterday.','was',['was','she','came']),
			new Question('I don\'t feel ____!','well',['well','did','but']),
			new Question('Our family ____ to the zoo.','went',['went','ate','was']),
			new Question('____ is it?','What',['What','Pretty','With']),
			new Question('Pandas are black and  ____.','white',['white','must','they']),
			new Question('____ is this boy?','Who',['Who','Well','Like']),
			new Question('I ____ go swimming tomorrow.','will',['will','brown','all']),
			new Question('I want to play ____ Mary.','with',['with','they','am']),
			new Question('Do you like ice-cream?____, I do.','Yes',['Yes','Get','Into']),
			new Question('I go to the library ____ school.','after',['after','let','thank']),
			new Question('I watched the cartoon ____.','again',['again','when','from']),
			new Question('____ elephant has big ears.','An',['An','Of','Put']),
			new Question('I don\'t see ____ fish.','any',['any','take','give']),
			new Question('I jump ____ high ____ a frog.','as',['as','know','an']),
			new Question('I ____ Miss Law a question.','ask',['ask','has','may']),
			new Question('He goes to school ____ bus.','by',['by','after','just']),
			new Question('____ I play with Tom?','Could',['Could','Fly','Stop']),
			new Question('I sleep at 9 o’clock ____ night.','every',['every','live','going']),
			new Question('Birds ____ in the sky. ','fly',['fly','from ','any']),
			new Question('I came home ____ school.','from',['from','stop','when']),
			new Question('Can you ____ us some candies?','give',['give','then','every']),
			new Question('We are ____ to China.','going',['going','once','how']),
			new Question('I ____ a great time.','had',['had','his','old']),
			new Question('A horse ____ four legs.','has',['has','her','let']),
			new Question('Mary loves ____ toy.','her',['her','them','him']),
			new Question('I give ____ my toys.','him',['him','how','after']),
			new Question('Tom puts on ____ shirt.','his',['his','know','from']),
			new Question('I know ____ to sing.','how',['how','from ','were']),
			new Question('I ____ ate a cake.','just',['just','when','as']),
			new Question('I ____ how to play the piano.','know',['know','once','some']),
			new Question('Please ____ me help you.','let',['let','her','think']),
			new Question('I ____ in Yuen Long.','live',['live','let','from']),
			new Question('You ____ go now.','may',['may','ask','every']),
			new Question('There are a lot ____ butterflies.','of',['of','an','has']),
			new Question('The ____ woman walks slowly.','old',['old','once','put']),
			new Question('I play football ____ a week.','once',['once','fly','every']),
			new Question('____ the door, please.','Open',['Open','Know','Some']),
			new Question('Mary jumps ____ Tom.','over',['over','old','live']),
			new Question('I ____ the book on the desk.','put',['put','over','from']),
			new Question('My mum has a ____ face.','round',['round','give','them']),
			new Question('Can I have ____ candies, please?','some',['some','how','know']),
			new Question('____ talking, please.','Stop',['Stop','Put','Her']),
			new Question('____ out a pencil, please.','Take',['Take','Has','When']),
			new Question('____ you very much!','Thank',['Thank','Round','After']),
			new Question('Could I play with ____?','them',['them','think','over']),
			new Question('I will eat lunch and ____ go to the park.','then',['then','going','think']),
			new Question('I ____ the duck is cute.','think',['think','let','open']),
			new Question('We ____ to school every morning.','walk',['walk','stop','live']),
			new Question('The children ____ in the playground.','were',['were','going','take']),
			new Question('____ is your birthday?','When',['When','Thank','From'])
		]
	}
}