class EasyQuestionRepository {
	public constructor() {
		
	}

	public getAll(): Question[]
	{
		// 0代表下划线在句子开头
		return [
			new Question('I drink ____ cup of milk every morning.','a',['a','an','the']),
			new Question('I have a dog ____ a cat.','and',['on','and','old']),
			new Question('Lily likes eating ____ .','beef',['beef','beefs','beefes']),
			new Question('I have a ____ dog.','big',['angry','big','go']),
			new Question('The sky is ____.','blue',['us','blue','day']),
			new Question('I ____ read.','can',['can','doesn\'t','red']),
			new Question('____ here.','Come',['Where','Come','Runs'], 0),
			new Question('Please keep ____ in the library.','quiet',['loud','play','quiet']),
			new Question('I can\'t ____ my ruler.','find',['find','finds','finding']),
			new Question('This gift is ____ you.','for',['for','at','through']),
			new Question('The clown is ____.','funny',['look','funny','tricks']),
			new Question('They ____ to school on foot.','go',['go','going','goes']),
			new Question('I always ____ my classmates.','help',['help','here','run']),
			new Question('Come ____, David.','here',['here','there','three']),
			new Question('____ am eating a banana.','I',['I','We','Them'], 0),
			new Question('The ball is ____ the box.','in',['it','red','in']),
			new Question('Andy ____ my friend.','is',['is','am','are']),
			new Question('We like ____.','it',['my','it','find']),
			new Question('We walked ____ the tunnel.','through',['off','across','through']),
			new Question('My ____ brother is cute.','little',['little','you','it']),
			new Question('____ at the butterfly.','Look',['See','Look','Take'], 0),
			new Question('My mum ____ a pie every Sunday.','makes',['make','makes','making']),
			new Question('My parents make a cake for ____ every year.','me',['I','me','mine']),
			new Question('Where is ____ pencil?','my',['me','my','mine']),
			new Question('This bag belongs to ____.','him',['he','his','him']),
			new Question('These shoes ____ new.','are',['is','am','are']),
			new Question('These are ____ towels.','your',['you','your','yours']),
			new Question('The apple is ____.','his',['he','his','him']),
			new Question('The students are ____ .','clapping',['clap','claps','clapping']),
			new Question('Nick is ______ his birthday cake.','cutting',['cuts','cut','cutting']),
			new Question('The baby is ____.','crying',['cries','crying','cry']),
			new Question('We are ____ for the school picnic.','planning',['plans','plan','planning']),
			new Question('I am ____ a bicycle.','riding',['ride','riding','rides']),
			new Question('We are walking ____ the park.','to',['to','after','between']),
			new Question('The toy shop is ____ the bank and the bakery.','between',['over','between','among']),
			new Question('We ran ____ the hill.','up',['up','at','with']),
			new Question('We sing carols ____ Christmas.','at',['at','behind','beside']),
			new Question('____ are you?','Where',['Where','Come','Little'], 0),
			new Question('Lemons are _________.','sour',['thick','sour','spicy']),
			new Question('How are ____?','you',['you','him','our']),
			new Question('I sleep ____ half past eight.','at',['on','in','at']),
			new Question('I ____ a good student.','am',['am','is','are']),
			new Question('They ____ my good friends.','are',['are','at','this']),
			new Question('School starts ____ September.','in',['on','in','of']),
			new Question('Ryan’s birthday is ____ 1 May.','on',['on','in','of']),
			new Question('Kelly ____ the violin every evening.','plays',['playing','play','plays']),
			new Question('The pen is on the top ____ the desk.','of',['on','under','of']),
			new Question('Ada is ____ a train to her cousin’s home. ','taking',['takes','taking','take']),
			new Question('I want to play ____ I can\'t.','but',['but','are','too']),
			new Question('Dad is ____ the bottle under the chair.','putting',['put','puts','putting']),
			new Question('Bob cleans the table ____ a towel.','with',['by','with','across']),
			new Question('____ you like swimming?','Do',['Do','Does','Can'], 0),
			new Question('They go to Korea ____ plane.','by',['at','with','by']),
			new Question('The birds are flying ____ the sky.','in',['on','in','behind']),
			new Question('The girls are playing ____ the swings.','on',['on','in','out']),
			new Question('You did a ____ job!','good',['good','like','she']),
			new Question('I ____ two lovely cats.','have',['am','has','have']),
			new Question('This cup is ____.','mine',['him','me','mine']),
			new Question('Roy and Angel ____ us to go to their party.','ask',['ask','asks','asking']),
			new Question('These rabbits are ____.','theirs',['them','their','theirs']),
			new Question('You ____ do your homework now.','must',['must','brown','what']),
			new Question('You  ____ litter.','mustn\'t',['must','mustn\'t','after']),
			new Question('"Do you like dogs?" "________, I don\'t."','No',['Yes','No','Do']),
			new Question('"Would you like an apple?" "______, please."','Yes',['Yes','No','No']),
			new Question('The ball is ____ the table.','on',['on','between','in']),
			new Question('____ family went hiking last Sunday.','Our',['Our','Ours','We'], 0),
			new Question('The fish jumps ____ of the tank.','out',['out','at','under']),
			new Question('May I eat this pancake, ____?','please',['sorry','please','good']),
			new Question('My sister is eating some ____. ','pasta',['pasta','pastas','pastaes']),
			new Question('My mum likes ____.','peaches',['peach','peachs','peaches']),
			new Question('Valerie loves ____.','berries',['berry','berrys','berries']),
			new Question('He read three ____ last night.','stories',['story','storys','stories']),
			new Question('Amy ____ at Happy Primary School.','studies',['study','studying','studies']),
			new Question('This hair clip is ____.','hers',['she','her','hers']),
			new Question('I am very ____ .','hungry',['hop','hungry','pizza']),
			new Question('Miss Chan is ____ now.','sitting',['sits','sit','sitting']),
			new Question('____ is my book.','That',['These','Those','That'], 0),
			new Question('____ are two cars on the road.','There',['There','Please','What'], 0),
			new Question('He ____ at home every night.','stays',['stay','stays','staying']),
			new Question('____ is my friend, Jane.','This',['This','These','Those']),
			new Question('"I enjoy reading science books." " Me, ____."','too',['too','two','three']),
			new Question('The cat is ____ the table.','under',['white','under','like']),
			new Question('John ____ to play with Tom.','wants',['want','wants','wanting']),
			new Question('Kate eats ____ every recess.','sandwiches',['sandwich','sandwich','sandwiches']),
			new Question('I don\'t feel ____!','well',['well','did','but']),
			new Question('There are eight ____.','boxes',['box','boxes','boxing']),
			new Question('____ is it?','What',['What','Pretty','With']),
			new Question('Pandas are black and  ____.','white',['red','white','they']),
			new Question('Mimi likes ____ .','tomatoes',['tomato','tomatos','tomatoes'], 0),
			new Question('Jill goes shopping ____ weekends.','at',['of','for','at']),
			new Question('I want to play ____ Erica.','with',['with','they','am']),
			new Question('Do you like ____?','rice',['rice','rices','riceses']),
			new Question('I go to the library ____ school.','after',['after','behind','on']),
			new Question('I watched the cartoon ____.','again',['when','again','from']),
			new Question('Those mice ____ big ears.','have',['has','have','are'], 0),
			new Question('I don\'t see ____ fish.','any',['many','take','any']),
			new Question('There are four ____.','buses',['bus','buses','busess']),
			new Question('Remember to bring your ____.','keys',['keyes','keys','keies']),
			new Question('He has a lot of ____.','toys',['toy','toys','toyes']),
			new Question('Polly is ____ behind the tree.','hiding',['hide','hides','hiding'], 0),
			new Question('My parents ______ kind to me.','are',['is','am','are']),
			new Question('The children ____ in the classrooms. ','are',['is','am','are']),
			new Question('I came home ____ school.','from',['from','stop','when']),
			new Question('His uncle is ____ him a red packet.','giving',['give','gives','giving']),
			new Question('We are ____ to China.','going',['go','goes','going']),
			new Question('Ben\’s cousins are walking with ____.','him',['he','his','him']),
			new Question('A horse ____ four legs.','has',['has','have','is']),
			new Question('Mandy likes ____ classmates.','her',['she','her','hers']),
			new Question('I give my clothes to ____.','them',['they','them','their']),
			new Question('Tom puts on ____ shirt.','his',['he','his','her']),
			new Question('I know ____ to dance.','how',['how','from','were']),
			new Question('I just saw ____ elephant.','an',['a','an','the']),
			new Question('There are many ____ on the farm.','cows',['cow','cows','cowes']),
			new Question('Please let me ____help you.','let',['let','lets','letting']),
			new Question('I ____ in Yuen Long.','live',['live','lives','living']),
			new Question('____ do you go to the library? ','How',['Who','Can','How'], 0),             	
			new Question('There are a lot ____ butterflies.','of',['at','of','has']),
			new Question('The ____ woman walks slowly.','old',['one','old','put']),
			new Question('I play football ____ a week.','once',['down','once','every']),
			new Question('____ the door, please.','Open',['Listen','Know','Open'], 0),
			new Question('Mary jumps ____ a doll.','over',['in', 'top', 'over']),
			new Question('I ____ the book on the desk.','put',['put','over','from']),
			new Question('My mum has a ____ face.','round',['give','round','them']),
			new Question('Can I have ____ sweets, please?','some',['a','an','some']),
			new Question('____ talking, please.','Stop',['Her','Put','Stop'], 0),
			new Question('____ out a pencil, please.','Take',['Take','Put','When'], 0),
			new Question('____ you very much!','Thank',['Just','Thank','Thanks'], 0),
			new Question('Could I play with ____?','them',['they','them','their']),
			new Question('I love eating ____.','vegetables',['fishes','vegetable','vegetables']),
			new Question('My sister likes eating ____ .','bread',['bread','breads','breades']),
			new Question('We ____ to school every morning.','walk',['walking','walks','walk']),
			new Question('Connie can____ well.','sing',['sing','sings','singing']),
			new Question('____ is your birthday?','When',['Why','When','Where'], 0),
		]
	}
}