class ProQuestionRepository {
	public constructor() {
	}

	public getAll(): Question[]
	{
		return [
			new Question('I ____ play football with my friends.','always',['today','likes','always']),
			new Question('Look! The bees are flying ____ the flowers.','around',['happy','around','many']),
			new Question('I like playing football ____ it is fun.','because',['because','after','before']),
			new Question('It  ____ raining now.','is',['are','don\'t','is']),
			new Question('Brush your teeth ____ you go to bed.','before',['before','front','under']),
			new Question('Jack is my ____ friend.','best',['under','best','very']),
			new Question('I like ____ of them.','both',['no','dance','both']),
			new Question('I usually ____ food in the supermarket.','buy',['buy','fast','off']),
			new Question('Please ____ me on the phone.','call',['come','call','sing']),
			new Question('It was ____ last week.','cold',['your','make','cold']),
			new Question('He ______ many books.','has',['have','has','is']),
			new Question('Sorry, I ____ know.','don\'t',['don\'t','doesn\'t','many']),
			new Question('Jason is a ____ runner.','fast',['wish','tell','fast']),
			new Question('He won the ____ prize.','first',['first','goes','why']),
			new Question('There are five ____ in the pond.','ducks',['swim','ducks','frog']),
			new Question('We ____ students.','are',['am','is','are']),
			new Question('Elsa ____ up early every morning.','wakes',['woke','wake','wakes']),
			new Question('Chloe ____ to school by bus.','goes',['go','going','goes']),
			new Question('The grass is ____.','green',['green','move','behind']),
			new Question('The dog likes ____ new house.','its',['it','its','it\'s']),
			new Question('Look! Felix is ____ now.','running',['runs','run','running']),
			new Question('How ____ apples do you have?','many',['many','much','are']),
			new Question('Please turn ____ the light.','off',['fast','at','off']),
			new Question('Do you like apples ____ pears?','or',['eat','or','buy']),
			new Question('Let\'s ____ the rope!','pull',['pull','pulls','pulling']),
			new Question('Can you ____ me a story?','read',['jump','watch','read']),
			new Question('"The answer is a zebra." "You are ____!"','right',['right','think','always']),
			new Question('Let\'s ____ a song.','sing',['talk','look','sing']),
			new Question('Please ____ down.','sit',['sit','sits','sitting']),
			new Question('Philip ____ housework every day.','does',['do','doing','does']),
			new Question('Please ____ me how to do it. ','teach',['put','talk','teach']),
			new Question('They like ____ teacher.','their',['them','their','theirs']),
			new Question('____ are Tom\'s pencils. ','These',['Their','Them','These'], 0),
			new Question('Put ____ books on the desk. ','those',['those','them ','us']),
			new Question('Once ____ a time, there was a boy.','upon',['right','call','upon']),
			new Question('Read ____ a story, please.','us',['we','us','our']),
			new Question('I ____ a spoon to eat.','use',['hear','work','use']),
			new Question('I am ____ tired.','very',['will','very','help']),
			new Question('____ your hands before you eat.','Wash',['Wash','Wish','Which'], 0),
			new Question('____ do you prefer, milk or apple juice?','Which',['Which','Drink','Those'], 0),
			new Question('____ do you like playing the piano?','Why',['Why','Sing','Can'], 0),
			new Question('I ____ you a Merry Christmas.','wish',['start','wish','speak']),
			new Question('The ants ____ very hard.','work',['work','works','working']),
			new Question('I feel ____ about the school picnic.','excited',['play','excited','exciting']),
			new Question('This game is ____ !','exciting',['careful','excited','exciting']),
			new Question('What is ____ name?','your',['you','your','yours']),
			new Question('Tell me ____ bats.','about',['about','in','up']),
			new Question('I feel ____ now.','better',['walk','drink','better']),
			new Question('I want to ____ this dog home.','bring',['bring','brings','bringing']),
			new Question('I ____ my bag to school every day.','carry',['come','climb','carry']),
			new Question('Please keep the school ____.','clean',['clean','funny','angry']),
			new Question('I ____ the tomato in half.','cut',['down','cut','ride']),
			new Question('I put some ____ on my bread.','cheese',['cheese','cheeses','butters']),
			new Question('I can ____ a pretty flower.','draw',['finish','draw','tidy']),
			new Question('My mum looks ____ me.','after',['before','after','out']),
			new Question('There are ten ____ in the bag.','oranges',['water','orange','oranges']),
			new Question('The teacher ____, “Open your book.”','says',['say','says','saying']),
			new Question('He lives ____ away from school.','far',['far','cut','six']),
			new Question('The basket is ____ of apples.','full',['fat','fall','full']),
			new Question('Emily____ shopping.','enjoys',['enjoy','enjoys','enjoying']),
			new Question('This plant ____ best under the sun.','grows',['grow','grows','growing']),
			new Question('Sally ____ her homework every night.','does',['do','doing','does']),
			new Question('I would like to have some ____ tea, please.','hot',['only','hot','far']),
			new Question('Ouch! I ____ myself!','hurt',['hot','hurt','small']),
			new Question('Harry is ____.','smart',['kids','friend','smart'], 0),
			new Question('Please ____ the park clean.','keep',['keep','change','grow']),
			new Question('” ____ do you go to school?” “By bus.” ','How',['What','Where','How'], 0),
			new Question('We ____ at the joke. ','laugh',['laugh','laughs','laughing']),
			new Question('Please turn on the ____.','fan',['chair','bath','fan']),
			new Question('Joanna has ____ hair.','long',['tall','long','dress']),
			new Question('I ate too ______ food last night.','much',['much','many','lots']),
			new Question('Amy is cooking with ____ sister.','her',['she','her','hers']),
			new Question('I ____ throw rubbish on the road.','never',['never','fall','very']),
			new Question('Bats ____ come out at night.','only',['hold','full','only']),
			new Question('We use ____ to colour the pictures.','crayons',['eraser','ruler','crayons']),
			new Question('Don\'t ____ the flowers.','pick',['much','allow','pick']),
			new Question('These pigs are ____ .','dirty',['carry','never','dirty']),
			new Question(' ____ is this girl?','Who',['How many','Why','Who'], 0),
			new Question('I can ____ you my picture.','show',['show','let','take']),
			new Question('I am ____ years old.','six',['son','fine','six']),
			new Question('Bees are ____.','small',['small','paint','keep']),
			new Question('Our lessons ______ at half past eight.','start',['starts','start','starting']),
			new Question('I have ____ fingers.','ten',['ten','flower','slow']),
			new Question('Tim ____ the dishes every night.','washes',['wash','washing','washes']),
			new Question('We play football ____.','together',['bring','together','small']),
			new Question('We will have dinner after ____ hour.','an',['a','an','the']),
			new Question('The soup is ____.','warm',['only','today','warm'])
		]
	}
}