(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.text41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAHBtQgJgFAAgIQABgLAIAAQAEABAIADQAHAAAAgGIAAgcIg3AAQgIAAAAgLQAAgIAGgCICKAAQAFABAAAKQAAAKgGAAIg7AAIAAAmQAAATgWAAQgKAAgIgDgAhQBoIAAhWQgGARgHALQgCABgEABQgJAAgDgNQAAgFACgEQAUgfAJgiIAAgDIgVAAQgJAAAAgOQAAgJAHgDIAXAAIAAgjQAAgIAMAAQALAAAAAIIAAAjIAOAAQAHADAAAKQAAANgJAAIgMAAIAAAEQARAUAHANIABAFQAAAKgNAAQgFAAgDgGIgEgKIAABtQAAAIgLABQgMgBAAgHgABdBrQgOgNgQgKQgHgEgBgGQACgLAKgDQAEAAAEAEQASALAPANQAEAEAAAFQAAANgLABQgEAAgEgEgAg0BeQABgDAHgEQAVgLALgNQAEgDADAAQAJACACAJQAAAEgDADQgHAMgVANQgJAHgGAAQgMgCAAgOgAgXAZQgHAAAAgMQAAgJAFgCIB7AAQAGABAAAKQAAAMgHAAgAgTgEQgNgDAAgOIAAgkQACgLAKgBIAYAAIAAgMIgiAAQgIAAAAgMQAAgJAGgCICIAAQAGACAAAKQAAALgHAAIgnAAIAAAMIAbAAQAOABAAAPIAAAfQAAARgOABgABAgaIARAAQAEAAAAgDIAAgQQAAgBAAAAQgBgBAAAAQgBAAAAgBQgBAAAAAAIgSAAgAAZgaIATAAIAAgWIgTAAgAgMgtIAAAPQAAABABABQAAAAAAABQABAAAAAAQABABAAAAIANAAIAAgWIgNAAQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAgBABgAAZhFIATAAIAAgMIgTAAg");
	this.shape.setTransform(82,36.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhSBqQgQAAAAgRIAAizQAAgPAQAAIClAAQAPAAABAPIAACyQAAASgQAAgAhJBMQABAFAEAAICJAAQAFAAAAgHIAAggIiTAAgAhJAQICTAAIAAgjIiTAAgAhJhMIAAAeICTAAIAAgcQAAgFgFAAIiJAAQgEAAgBADg");
	this.shape_1.setTransform(58,36.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhkBtQgJAAABgOQgBgKAHgCIDOAAQAHACAAALQAAANgIAAgAhHBLQgQgDAAgPIAAg+IABgEIgCABQgJADgDAAQgKgCAAgPQAAgFAEgDQA7gSAYgTIhLAAQgIAAAAgNQAAgJAGgCIBZAAIAAgIQAAgJAMABQAMgBAAAJIAAAIIBZAAQAGABABALQAAAMgIAAIhIAAQAeAYAsAJQAHAFAAAFQgBAJgDADQgDAEgHAAIgIgDQACAFABAFIAAA5QAAASgSABgAg+AwQAAAEADAAIB4AAQAFAAAAgEIAAgKIiAAAgAg+AGIAAALICAAAIAAgKQgBgDgDgBIh5AAQAAAAgBABQAAAAgBAAQAAABgBAAQAAABAAAAgAANgWIgBAEIA1AAQgfgMgVgSgAg/gSIA0AAIAAgDIAAgbQgVARgfANg");
	this.shape_2.setTransform(34,36.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAsBdQgjASgtABQgKAAgBgKQAAgJADgEQADgDAJAAQAcgCAQgFQgYgNgKgIQgDgFgBgEQACgMAKABIAMAGQAWANAWAKQAXgNAHgSQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBAAAAIhfAAQgJAAAAgMQAAgIAHgCIAzAAIgBhyQAAgJAMABQALAAAAAIIABByIAlAAQAMAAAAAQQgBAbgcAXIAkALQAIACABAIQgBAIgDADQgBADgKABQgMgBgqgTgAhuBjQAAgGACgFQAEgDAFAAIAIACQALAAAAgHIAAgxQgKADgJABQgIAAgBgFQgCgGAAgFQAAgFADgBQAPgFAMgEIAAgwIgXAAQgIAAAAgNQAAgJAGgCIAZAAIAAgkQACgHAKAAQAMAAAAAIIAAAjIANAAQAIACgBAKQAAAMgIAAIgMAAIAAAnIAMgHQAFAAADACQAEAFAAAFQAAAGgEABQgBAGgTAIIAABJQAAAOgPACIgQAAQgXAAAAgLgAgTAAQgPAAAAgSIAAg/QAAgHAGgFIAigLQAMAAgBAOQAAABAAABQAAABAAAAQAAABgBAAQAAABAAAAQgDAFgNACQgLACgBADIAAAMIAXAAQAHAAgBALQAAALgGAAIgXAAIAAAMQAAADADACIAUAAQAJABgBAJQAAAMgIAAgAA7gBQgHAAAAgLQABgKAGAAIASAAQAIAAAAgIIAAgJIgYAAQgHgBAAgLQAAgLAHAAIAYAAIAAgKQAAgFgFAAIgTAAQgJAAABgLQAAgKAHgBIAeAAQAPAAACAOIAABEQgBAQgOAAg");
	this.shape_3.setTransform(10,36.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AADBoIAAilIgHAAQgHAegKARQgEAKgGAAQgMAAgFgKQAAgGACgFQAUgnAEgnQADgIAIAAQANAAAAAJIgCAKIAAAFIBoAAQAIABAAALQgBAOgHAAIhLAAIAAAjIBDAAQAHAAAAALQAAAOgHAAIhDAAIAAAkIBEAAQAIABgBAKQAAANgHAAIhEAAIAAAsQAAAJgNAAQgNABAAgJgAhRBoIAAhxIgDADQgEAJgGAAQgNAAgDgJQAAgGACgEQAfgsAIgsQACgHAKgBQANABAAAIQAAAGgCAEQgEAUgGAPIAACiQABAJgMgBQgMAAgCgIg");
	this.shape_4.setTransform(202,10.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhbBrQgNAAAAgMIAAi8QACgNALAAIC3AAQAKABAAALQAAANgLAAIinAAQgDAAAAAFIAACaQABAEAEAAICqAAQAKABAAAMQAAAMgMAAgAAiBJQgMgBgBgLIAAg1QAAgKANgBIA0AAQANABAAAMIAAAyQAAANgOAAgAAsAUIAAAcQAAAEAGAAIAVAAQAFAAAAgEIAAgbQAAgFgFAAIgYAAQgBAAAAABQgBAAAAAAQAAABgBABQAAAAAAABgAg3BJQgNgBgBgLIAAg1QAAgKAOgBIA0AAQALABAAAMIAAAyQAAANgNAAgAguAUIAAAcQAAAEAGAAIAVAAQAGAAAAgEIAAgbQgBgFgFAAIgYAAQAAAAgBABQAAAAgBAAQAAABAAABQgBAAAAABgAglgLQgPgCAAgOIAAghQADgLALgBIBmAAQARACAAANIAAAeQAAAQgRAAgAgcgxIAAAOQAAABAAABQABAAAAABQABAAAAAAQABABAAAAIBNAAQAFAAAAgDIAAgPQAAgBAAAAQgBgBAAAAQgBAAAAgBQgBAAgBAAIhOAAQAAAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABg");
	this.shape_5.setTransform(178.5,10.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgGBnQgRgFABgdIgBhHIgIACQgLAAAAgNQAAgFACgEIARgHIAAg5QABgEAKgBQAMAAABAFIAAAtIAXgLIAAgxQAAgIANAAQALAAAAAIIAAAmIApgSQAKAAACAKIACA/QgBAVgCAJQgCAMgFADQgHAHgUABQgIAAgBgDQgDgFgBgFQAAgJAGgCQARgDABgFQACgCAAg2QAAgFgFAAIgaAMIAABZQAAAJgLAAQgNgBAAgHIAAhPIgXALIAABNQAAASANABQARADAJAAQAOAAAMgDQATAAAAgQIAAgQQADgIAKABQANAAAAAHIAAAXQAAAfgfAEIglACQgkgBgNgGgAhsBjQgBgEgBgFQAAgGAEgFIAWgKIAAhkIgRAAQgIAAgBgNQAAgKAIgCIASAAIAAgrQAAgJANAAQANAAAAAJIAAArIAQAAQAHACAAAKQAAANgIAAIgPAAIAABWQAMgGACgBQAIAAAAADQAGADgBAJQAAAFgDADQgGAGgVALQgeARgGAAQgHgBgEgFg");
	this.shape_6.setTransform(153.9,10);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhlBsQgGgEgCgJQAAgEADgFIAXgRIAAgvQAAgFgFAAIgNAAQgJgBAAgMQAAgLAIgBIAfAAQAMABAAAMIAAA0QACAIALAGQAAgFACgDQAWgFAMgLIgmAAQgIAAAAgNQAAgJAGgCIAhAAIAAgLIgdAAQgIAAAAgMQAAgHAGgCIAfAAIAAgHIABgEIgTAAQgQAAAAgSIAAg0QAAgOAQgCIApAAQAOABABARIAAASQAAALgHAEQAKABAAAFIAAAJQAAAUgUAAIgBAAQABABAAAAQAAABAAAAQABABAAABQAAAAAAABIAAAGIAoAAIAAgGQAAgBAAAAQAAgBABgBQAAAAAAgBQAAAAABgBIgDAAQgPAAgBgSIAAgzQAAgOAQgDIAqAAQAPACABAQIAAASQAAAIgEAEIACAAQALAAAAAHIAAALQAAAUgVAAIgYAAIACAFIAAAGIAfAAQAGABAAAJQAAALgGAAIgfAAIAAALIAiAAQAGABAAALQAAAMgHAAIgjAAIAeAPQAGAFAAAFQAAAHgDADIACAAQAJABAAAMQAAAMgJAAIg7ABQhUAAgZgUQgYAWgFAAQgEAAgBgCgAAJA4QAAAEgEADQgLALgKAFQASAEAaAAIA3AAIgggSQgFgCgBgFQABgIADgDIgtAAQAEADABAGgAAFAXIAoAAIAAgLIgoAAgAAwgvQAAAHAIAAIAZAAQAIAAAAgKIAAgBIABgCIgFABIglAAgAgfgvQAAAHAIAAIATAAQAGAAABgIIAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAIgjAAgAAwhQIAAAIIAcAAQAEAAABgFIAAgDQAAgEgEgBIgZAAQgDACgBADgAgfhQIAAAIIAbAAQAEAAAAgFIAAgDQAAgEgDgCIgYAAQgDACgBAEgAhRgXQgJgIgLgHQgIgFAAgFQACgMAKgDQAEAAAFAEQAMAIAKAJQAFADAAAGQAAANgMABQgEAAgEgEgAhPhGQgJgHgLgGQgIgFAAgGQACgMALgDQADAAAFAEQAMAIAKAIQAEADAAAFQAAAOgLABQgEAAgEgEg");
	this.shape_7.setTransform(130.1,10.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhuBnQAHgXADgcQACgDAHgBQAKAAAAAGQgBAdgIAWQgCAFgJABQgIgBgBgHgAhEBkQgEgZgEgNIgBgJQAEgFAGAAQAGAAACAEQAGANAEAgQAAAGgDACQgDACgHAAQgGAAAAgHgAAXBqQgNABgBgQIAAhcQAAgOANgBIATAAIAAhVQAAgHALgCQANABAAAIIAAAYIAnAAQAHAAAAALQAAAOgIAAIgmAAIAAAkIAdAAQANACAAAOIAABaQAAARgOgBgAAgANIAABAQABAFAFAAIApAAQAFgBAAgEIAAg/QAAgGgFAAIgpAAQgFAAgBAFgAgmBgQgEgYgFgMIgBgIQAEgFAGgBQAGABADAEQAFAMAFAdQAAAHgDABQgDACgHAAQgGAAAAgGgAgKBQQgEgQgEgHIgBgJQAEgGAGAAQAFABADAEQAEAJAEAWQAAAFgDACQgDACgGAAQgFAAAAgHgAhuAhQAAgHAEgEIAsgCIAAgNIgmAAQgIABAAgKQAAgJAGgBIAoAAIAAgKIgeAAQgMAAgBgNIAAg7QAAgMANgBIBWAAQALACAAANIAAA4QAAAOgMAAIgiAAIAAAKIApAAQAGABAAAJQAAAKgGgBIgpAAIAAAMIAmgDQAHABABAKQAAAIgDABQAAACgsADIg7ADQgIAAgBgLgAgpgrIAVAAQAFAAAAgEIAAgiQAAgFgFABIgVAAgAhUhSIAAAkQABADAFAAIAQAAIAAgqIgSAAQgDAAgBADgAgng2IACgEQADgJABgKQABgFAFAAQAEABACABQADACAAACQgBAOgFAMQgCADgEABQgIgBgBgHgAhNg0QgCgOgDgHIAAgGQACgDAEgBQAEAAACADQADAIADARQAAAFgCABQgCABgFABQgEgBAAgEg");
	this.shape_8.setTransform(106,10.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag5BqQgOgBgBgPIAAglQgKAHgMAFIgHABQgJgEgCgKQAAgEAFgGQAmgRATgVIgmAAQgJgBAAgKQgBgKAJgBIA4AAQAFgLABgLIhLAAQgHAAgBgMQAAgJAHgCIBNAAIAAgSIg6AAQgKAAAAgMQAAgLAJgBICjAAQAMAAAAARIAAAZIARAAQAGABAAALQAAALgHAAIgQAAIAAAdQgBAOgLABIhfAAQgHALgJAKIBzAAQAOAAABANIAAAzQAAAQgPABgAgwA0IAAAaQACAEAEAAIBuAAQAFAAAAgGIAAgWQAAgFgFgBIhuAAQgFAAgBAEgAgGgSIBDAAQAFAAAAgGIAAgQIhEAAQgBAMgDAKgAgCg/IBEAAIAAgLQAAgHgEAAIhAAAg");
	this.shape_9.setTransform(81.9,10.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhABeQAAgEADgIQADgEAFAAQATAEAOACQAMAAAAgZIAAiiQAAgIANAAQANAAABAIIAACmQgBAogQAFQgDAEgPAAQgtAAgDgSgAhqA/QgEgEgBgGIAZhCIAQg0QAEgEAGAAQANAEAAAKQgBAUgTAxQgPAugGAEQgEAEgFAAQgGgBgDgEgABTA5QgMhDgQglIgDgGQAAgPAOgBQAJABAEAIQAIATAVBOQACAEABAOQAAAMgQABQgKAAgCgLg");
	this.shape_10.setTransform(57.9,10);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhKBvQgPgCAAgRIAAg+IABgEIgEABQgNgBgBgNQAAgEACgDQAYgOAIgYIgdAAQgIAAAAgMQAAgJAGgBIAjAAIAAgEIAAgMIgeAAQgIAAAAgMQAAgJAGgCIAgAAIAAgJQACgHAKgBQAMAAAAAJIAAAIIAfAAQAGABAAALQAAALgHAAIgeAAIAAAQIAkAAQAFAAAAAKQABAMgHAAIgiAAQATANAPALQADAFAAADQgDAOgKAAQgFgBgEgEQgNgLgMgKQgIAQgQANIACAAIBQAAIgDgIQAAgDADgEQAVgNAIgVIgZAAQgJAAABgMQgBgJAHgBIAfAAIABgGIAAgKIgaAAQgIAAAAgMQAAgJAGgCIAcAAIAAgJQABgHALgBQANAAAAAKIAAAHIAkAAQAGABAAALQAAALgGAAIgkAAIAAAMIAAAEIAnAAQAHAAAAAKQAAAMgIAAIgeAAQARAUARAMQAEADAAAGQgBAOgOAAQgFgBgEgEQgNgKgSgYQgIATgSAOIAsAAQARACABAPIAAA6QgBASgRABgAhCBTQABAEADABIB8AAQAFgBAAgDIAAgKIiFAAgAhCArIAAAJICFAAIAAgJQgBgDgDAAIh9AAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABgBABg");
	this.shape_11.setTransform(34.1,10);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhuBhQABgKAFgDQAtgTAIgfQAEgGABgTIg1AAQgJAAAAgOQAAgKAHgCIBdAAIAAgjIg7AAIgCABQgTAdgHAAQgKAAgEgOQAAgFAFgFQAWgZAQggQACgGAHAAQAPADAAAKQAAAFgIAMIAqAAIAAgXQAAgIAMgBQANAAAAAKIAAAWIBRAAQAHABAAALQAAAOgIABIhPAAIAAAjIBXAAQAGABAAAMQAAAMgHABIg9AAIAAA+QAAAKAKAAIASAAQANgBAAgQIAAgRQADgGALAAQAMAAAAAIQAAAXgBAPQgEAUgYABIgqAAQgTgBgDgRIAAhRIglAAQgDAggIAOQgLAdgqAYQgGADgGAAQgMAAgCgOg");
	this.shape_12.setTransform(9.9,10.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4,-3.8,243.1,81.2);


(lib.text38UpOverDownHit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D2A9FF").s().p("AkKGZQhBgtAAhAQAAgoAWgfQAXgfAnAAQAhAAAQARQAQAQAAAUQAAAbgOAcIgXAuIANAOQAJAJAQAIQARAJAZAHQAZAGAgAAQApAAArgTQArgTAgghQAjglAVgyQAUgyABhGQAAg5glgdQgmgehIAAIhRAAIAQhEIA2AAQBfAAA3hCQA3hDAAhjQAAg4gcgdQgcgeg5AAQgrAAgiARQgiAQgTAUIABAWIAAAeQAAA8gZAbQgYAcgyAAQgdAAgMgPQgNgQABgYQAAgkAUgjQAWgjAqghQAmgfA9gVQA7gVBFAAQA/AAArARQArARAYAaQAXAZAKAdQAIAeABAcQAAAfgNAmQgNAmgYAdQgaAhgsAbQgsAchAAQIgDAKQAeACAhAMQAhAKAZARQAcAUAQAfQASAfgBArQAABGgfA8QghA6g0AoQg3AqhFAXQhFAWhOAAQhjAAhAgrg");
	this.shape.setTransform(30.3,91.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4,-3.4,78.3,290.3);


(lib.text34UpOverDownHit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF9A00").s().p("AlvF6IAWhdQAVgcAdgaQAcgaAngYQAjgVAqgVQAqgUAxgTQA+gZAwgXQAvgYAhgZQAygkAVgrQAVgsAAg6QAAhDglgnQglgog7AAQg4AAgnAUQgoAUgPAWIABAXIABAlQAAA9gZAfQgYAeg0AAQglAAgPgRQgPgSAAgZQAAgoAZgpQAZgqAugkQAsgjA/gVQA8gWBJAAQB0AABIA6QBHA5AABjQAABMglAzQglAzhAAkQgvAbg/AWQg/AUhMAXQhAATg8AcQg+AcgnApIIgAAIgbB3g");
	this.shape.setTransform(34.8,89.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4,-3.4,87.1,322.2);


(lib.text31UpOverDownHit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#99FF66").s().p("AjwF6IALgtIBBgGQAsgFASgEQATgGARgSQASgTAGgaIBvnlIiqAAIANg2IAmAAQBGAAA9gYQA/gZAogmIA5AAIgfB2IgYBdIheGYIgCALIgBAMQAAASAIAMQAJAMALAFQAOAHAmAGQAnAGAWACIgKAtg");
	this.shape.setTransform(22.9,89.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4,-3.4,64.2,322.2);


(lib.text25DownHit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AhcCIIAAh9IC9AAIAAB5IgZAAIAAgLIiLAAIAAAPgAhDBhICLAAIAAg+IiLAAgAiMgOQBcgjArg/IiAAAIAAgXIENAAIAAAXIhuAAIgMASIAABcIgYAAIAAg/QgvAzhKAZgAAcg1IAOgVQA3ATAsAgIgPAXQgygigwgTg");
	this.shape.setTransform(13.8,15.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4,-3.9,40.5,74.8);


(lib.text23Over = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCCCC").s().p("AhoCZIAAiNIDVAAIAACJIgcAAIAAgNIicAAIAAARgAhLBuICcAAIAAhHIicAAgAidgQQBngnAxhHIiRAAIAAgaIEvAAIAAAaIh8AAIgNAUIAABoIgbAAIAAhIQg1A6hTAcgAAgg8IAPgYQA+AWAxAkIgRAaQg4gng1gVg");
	this.shape.setTransform(15.8,18.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4,-3.8,44.8,83.8);


(lib.text22Up = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AhoCZIAAiNIDVAAIAACJIgcAAIAAgNIicAAIAAARgAhLBuICcAAIAAhHIicAAgAidgQQBngnAxhHIiRAAIAAgaIEvAAIAAAaIh8AAIgNAUIAABoIgbAAIAAhIQg1A6hTAcgAAgg8IAPgYQA+AWAxAkIgRAaQg4gng1gVg");
	this.shape.setTransform(15.8,18.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4,-3.8,44.8,83.8);


(lib.text19DownHit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0000FF").s().p("AiDBrQAugUAQg+IAaAHQAEAEgIABIgIAWQAXAZAaAJIAAhQIhzAAIAAgVID8AAIAAAVIh0AAIAAAbIBVAAIAAAWIhVAAIAAAmIB1AAIgGAWIheAAQg+AAgigsQgYAlgdAOgAhTgbIAAhlICrAAIAABlgAg7guIB8AAIAAgWIh8AAgAg7hXIB8AAIAAgWIh8AAg");
	this.shape.setTransform(13,14.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4,-3.9,38.4,70.5);


(lib.text17Over = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#99FFFF").s().p("AidCAQA3gYAThKIAfAIQAGAGgKABIgKAZQAbAfAfAKIAAhfIiKAAIAAgaIEvAAIAAAaIiKAAIAAAgIBlAAIAAAbIhlAAIAAAtICLAAIgHAaIhwAAQhLAAgpg0QgcAsgjARgAhjghIAAh5IDNAAIAAB5gAhHg3ICVAAIAAgbIiVAAgAhHhoICVAAIAAgbIiVAAg");
	this.shape.setTransform(15.9,17.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4,-3.8,44.8,83.8);


(lib.text16Up = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0000FF").s().p("AidCAQA3gYAThKIAfAIQAGAGgKABIgKAZQAbAfAfAKIAAhfIiKAAIAAgaIEvAAIAAAaIiKAAIAAAgIBlAAIAAAbIhlAAIAAAtICLAAIgHAaIhwAAQhLAAgpg0QgcAsgjARgAhjghIAAh5IDNAAIAAB5gAhHg3ICVAAIAAgbIiVAAgAhHhoICVAAIAAgbIiVAAg");
	this.shape.setTransform(15.9,17.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4,-3.8,44.8,83.8);


(lib.text14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AA6CCQgEgEAAgIQAAgHAFgGQAEgDAFAAQAPAEAIABQANAAAAgTIgJADQgHAAgEgGQgIgVgFgNQgCgCAAgFQAAgIAKgDQAIAAADAEQAGAHAJAXIAAgjQAAgFgEgBIh6AAQgOAAAAgPIAAiFQACgOANAAICRAAQAMABAAAMQAAAPgMABIg7AAIAAAQIA1AAQAHAAABANQgBAQgIAAIg0AAIAAAOIA1AAQAIABAAAMQAAAQgJAAIg0AAIAAARIA1AAQARACABALQAABsgJAAQgHASgaAAQgdgBgIgGgAgGgHQAAABAAABQAAABAAAAQAAABABAAQAAAAAAABIAqAAIAAgRIgrAAgAgGgwIArAAIAAgOIgrAAgAgGhmIAAALIArAAIAAgQIgpAAQgCAAAAAFgAg4B0QAAgDADgGQAMgaAFglQADgIAIAAQAHAAADACQAEAEAAAEQgCArgQAgQgCAIgJAAQgPAAgBgNgAAEBwQgEglgCgUIgCgMQAEgHAJAAQAIAAAEAHQAFASAFAvQAAAJgDACQgFADgLAAQgHAAgBgKgAAqBcQgEgZgFgMIgBgNQAEgHAKAAQAIAAAEAGQAHANAFAiQAAAIgEADQgEACgLAAQgHAAgCgJgAh3BjQgQAAgBgTIAAi5QAAgTAQgBIA3AAQARACgBAUIAAC1QAAAVgRAAgAhrhWIAACTQAAAGAHAAIAQAAQAHgBAAgGIAAiRQAAgHgHAAIgQAAQgFAAgCAGg");
	this.shape.setTransform(193.3,16.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiECCIAAj4QADgUAVAAIBHAAQAYAAABASIAABGQgCAUgXAAIhBAAIAACeQAAALgPAAQgMAAgDgJgAhmg7IA2AAQAHAAAAgGIAAgGIg9AAgAhmhpIAAAGIA9AAIAAgFQAAgGgFABIgzAAQgGAAABAEgABACDQgHgBgEgJIACgMQACgGAIgCQAOAEALABQANAAAAgNIAAh7IhJAAQgVAAgBgYIAAg6QAAgUATgEIBRAAQAYAAABAWIAADTQAAAYgJAIQgCAJgbAAQgUAAgLgHgAAlhAQABAGAGgBIA7AAIAAgNIhCAAgAAlhoIAAAGIBCAAIAAgGQgBgFgFAAIg3AAQgEAAgBAFgAhVBvQAAgGAJgHQAKgIAJgSQACgDABgHIgeAAQgJAAAAgQQgBgLAIgCIAiAAIAAgYIgbAAQgJAAgBgPQAAgLAIgCIChAAQAHABAAANQAAAOgIAAIgfAAIAAAYIAmAAQAIABAAANQAAAPgJAAIglAAIAAA1QAAAKgOAAQgPAAAAgKIAAg1IguAAQgFAngaAXQgFAEgIAAQgMgBgCgQgAgYAhIArAAIAAgYIgrAAg");
	this.shape_1.setTransform(163.2,16.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AiICAIAAhlQAAgSASAAIAnAAIAEgLIglAAQgRgBgBgRIAAg9QADgHAIgBQANABACAHIAAAwQAAAGAJAAIABAAQgEgDgCgIQABgDACgDQAIgHAGgHIgKgHQgFgDgBgFQABgMAJgEIAEAAIAUAPIAPgQQADgCADAAQAOADgBALQABAEgQAPIAMAJQAGAFAAAFQAAAKgEADQAKAAAAgIIAAguQAAgKAMABQAMAAAAAJIAAAcQAagjAMgoQADgJAHABQAQAAABAIQAAAIgBAFIgJAXIAWAAQAIgRAGgWQAEgEAGAAQAKABACAEQAEAEAAAFQgEASgFALIAUAAQAIAAAAANQAAAQgJAAIgbAAIAAAhIAbAAQAIABAAANQAAAQgJAAIgaAAIAAAkIAbAAQAIAAAAAMQAAAPgIAAIgbAAIAAAoIAaAAQAJAAAAAPQAAAPgJAAIhbAAQgSAAgBgSIAAiQQgDACgFABQgFAAgDgCIAAAIQAAAQgRACIgiAAIAAACIgCAJIApAAQARAAABASIAABPQAAAfgUAAQgRAAgPgDQgJgBgDgFQgCgEAAgHQAAgIAIgCQAKACAOABQAHAAgBgGIAAgIIgGACQgGAAgEgGIgDgGQgWAKgZADQgPABgEAAIgCAAIAAAcQgDAKgLAAQgNAAgCgKgAAvBgQABAHAHAAIASAAIAAgoIgaAAgAhrAlIAAAlIAIgBIANgnIgRAAQgBAAgBABQgBAAAAAAQgBABAAAAQAAABAAAAgAggAtQAFAFAHAVIAAggQAAgFgEABIgjgBIgDAJIgJAaIAWgGIgCgFQgBgCAAgFQAAgJAJgCQAJAAACAFgAAvAkIAaAAIAAgkIgaAAgAhQgbIAiAAIgQgPQgMALgGAEgAAvgeIAaAAIAAghIgaAAgAiAheQgJAAAAgOQAAgKAHgCIA3AAIAAgGQABgJANgCQAOABAAAKIAAAGIAyAAQAIACAAALQgBANgIAAg");
	this.shape_2.setTransform(132.9,15.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAgByIgVgFQglAYhkACQgIgCgCgLQAAgIAEgGQACgDAKAAQAugCAhgGQgsgLgBgEQgCgEgBgGQABgFAEgEQAJgJALgNIg+AAQgJAAgBgQQABgLAHgCIBXAAIAMgRIhHAAQgTgDAAgTIAAgqQACgQAQgBIAzAAIAAgTIhKAAQgKAAAAgQQAAgLAHgDID9AAQAIACAAANQAAAPgJAAIhMAAIAAATIAyAAQAVACABATIAAAlQgBAWgVABIhhAAIAAAFIgFAMICEAAQAIABAAAOQAAAOgJAAIgsAAQgPAcgbATQAuAKAjAGQAMAEAAAIIgBAIQgBAMgOAAQg8gOgbgIgAgqBDQAAADAFABIApAJQAigVAMgSIhHAAIgVAagAAxghIAkAAQAFAAAAgEIAAgRQAAgEgFAAIgkAAgAgVghIAoAAIAAgZIgoAAgAhZg2IAAAQQABAEAEABIAiAAIAAgZIgiAAQgDAAgCAEgAgVhWIAoAAIAAgTIgoAAg");
	this.shape_3.setTransform(103,16);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAdCEQgUgEgCgDQgEgFAAgKQAEgNAKAAIAbAFQAVAEAHAAQAKAAAEgKQANgJABiVQAAgIgIgCIg/AAQgJAegMATQgGALgFAAQgJAAgFgDIAAB7QAAAUgTAAIhLAAQgTAAAAgTIAAi6QAAgSATAAIAUAAIALgkQADgFAGAAQAHAAAFADQAEADABADQACAEAAAEIgHAYIAWAAQATAAABARIAAAjQAWgpAFgqQADgKALAAQARAAAAALQAAAHgCAFIgBAHIBKAAQATABAAARQAABcgFA1QgGA5gKAHQgIAPgdABQgTAAgZgFgAhkBdQABAGAGAAIAoAAQAGAAAAgIIAAhBIg1AAgAhkg9IAAA6IA1AAIAAg4QgBgGgFAAIgpAAQgFAAgBAEgAAwA2QgLgvgMgXIgDgHQAAgRAPgBQAKABAEAIQAHANARAyQACAFACAPQAAAOgSABQgMAAgBgMg");
	this.shape_4.setTransform(73.1,15.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AB1CJQgegIhAgNQgEgCAAgFQAAgJAFgEIgvAAQACAEAAAHQAAADgCADQgCADgGABQgZAOhAAGQgFAAgDgBQgIgCAAgPQAAgGAGgEQA0gGAdgHIgyAAQgYAAgFgYIAAh2QADgKAMgBQAPABACAKIAABtQAAAFALAAIDUAAQAKADAAAKQAAAPgLAAIhEAAIBGAMQAIAEAAAGQAAAKgEAGQgCADgFABIgIgBgAg+A5QgTgCgBgQIAAhOQADgNAQgBICnAAQAWACAAAPIAABLQAAASgWAAgAgzAeQABAFADAAICJAAQAGAAAAgDIAAgHIiTAAgAgzAHICTAAIAAgIIiTAAgAgzgbIAAAHICTAAIAAgHQgBgDgFAAIiJAAQgCAAgCADgAAGg+QhMABgEgDQgegCgBgkIAAgaQACgIAMgBQAQAAAAALIAAABQBqAAA6gLQAHAAADADQAEAFAAAGQAAAIgIAEQgsAIh9ACQAEAKANAAQAgACAtAAIA6gBQAYgBAAgHIABgKQADgJAMAAQAPAAAAAJIgBARQgCAagrACIhRAAg");
	this.shape_5.setTransform(42.9,15.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhoCBIAAiKIgCADQgFALgHAAQgQAAgFgLQABgIADgGQAng2AJg2QACgJAMAAQAQAAAAAKQAAAHgCAGQgGAbgIAWIAADCQAAAJgPAAQgNAAgDgJgAgNB+QgEgCAAgPQACgJAIAAQAOAFANABQAJAAAAgNIAAifIglAAQgKAggQAUQgFALgGAAQgPAAgFgLQAAgIADgFQAegyAHgxQADgKAMAAQAQAAAAAKQAAAIgCAFIgDAQIByAAQAYABAAAZQgDAXgOAcQgCAHgJAAIgDAAQAJAYAQA9QACAFACAQQAAAOgTAAQgMAAgBgMQgNhDgRgkIgCgHQAAgRAQgCIAGACIACgCQAHgUABgFQAAgGgEgBIgnAAIAACjQAAAggRAFQgHAEgNAAQgfgCgHgKgAg2BeQAAgIADgFQAdg1AIg0QACgJAMAAQAOAAABAKQAAAHgCAFQgNBGgWAjQgFAMgHAAQgPAAgFgMg");
	this.shape_6.setTransform(13,15.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4,-3.9,263.7,70.5);


(lib.text7Over = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF3300").s().p("Ah7B5IAAjoQACgRAVgBIBCAAQAXABAAAQIAABBQgCATgVAAIg9AAIAACTQAAALgOgBQgLABgDgJgAhfg3IAyAAQAHAAAAgGIAAgGIg5AAgAhfhhIAAAEIA5AAIAAgEQAAgFgFAAIgvAAQgFAAAAAFgAA8B6QgHAAgDgJIACgLQACgHAHgBQANAEALABQALAAAAgNIAAhyIhEAAQgTAAgBgXIAAg1QAAgTARgEIBNAAQAVAAABAVIAADEQAAAXgIAIQgCAIgaAAQgRgBgLgGgAAjg7QABAEAFAAIA3AAIAAgNIg9AAgAAjhhIAAAFIA9AAIAAgEQAAgGgFAAIgzAAQgFABAAAEgAhPBoQAAgGAIgHQAKgHAIgRQACgEABgGIgcAAQgJAAAAgOQAAgKAHgCIAgAAIAAgYIgZAAQgJAAAAgNQAAgKAHgCICWAAQAHABAAAMQAAAMgIAAIgdAAIAAAYIAkAAQAHABAAANQAAANgJgBIgiAAIAAAyQAAAKgNAAQgOgBAAgIIAAgzIgqAAQgGAlgYAVQgFAFgHAAQgLgCgCgOgAgWAfIAoAAIAAgYIgoAAg");
	this.shape.setTransform(40.1,15);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF3300").s().p("Ah/B4IAAhfQAAgRARAAIAkAAIAEgKIgjAAQgQAAgBgRIAAg5QADgHAIAAQANAAAAAHIAAAtQAAAGAJAAIABAAQgEgEgBgGQAAgEACgCIAOgNIgJgHQgGgCAAgFQABgMAIgDIAEAAIASAOIAOgPQACgDADAAQANAEAAAKQAAAEgNAOIAKAIQAGAFAAAFQAAAIgEAEQAJgBAAgGIAAgsQAAgIAMAAQALAAAAAIIAAAbQAZghAKglQADgJAHAAQAPAAABAIQAAAHgCAGQgEALgEAKIAVAAQAHgQAGgUQADgEAGAAQAJABACAEQAEADAAAFQgEARgFAKIATAAQAIAAAAANQAAAOgJAAIgaAAIAAAfIAaAAQAIABAAAMQAAAOgJAAIgZAAIAAAiIAaAAQAIAAAAAMQAAAOgIAAIgaAAIAAAlIAZAAQAJAAAAAPQAAANgJAAIhVAAQgQAAgBgRIAAiGQgEACgEAAQgFAAgCgCIAAAIQAAAQgRABIgfAAIAAABIgCAJIAnAAQAQAAABARIAABKQAAAdgTAAQgQAAgPgEQgIAAgCgFQgCgDgBgHQABgHAHgDIAWAEQAHAAAAgGIAAgIIgHACQgGAAgDgFIgCgGQgVAJgYAEIgRAAIgCAAIAAAaQgCAKgLAAQgNAAgBgJgAAsBZQABAHAGAAIARAAIAAglIgYAAgAhkAjIAAAiIAHAAIAMglIgPAAQgBAAgBAAQAAAAgBABQAAAAgBABQAAAAAAABgAgeApQAFAFAHAUIAAgeQAAgEgFAAIggAAIgDAHIgIAZQALgCAKgDIgDgFQgBgCAAgFQAAgHAJgDQAIAAACAEgAAsAhIAYAAIAAgiIgYAAgAhLgZIAgAAIgPgOQgLAKgGAEgAAsgcIAYAAIAAgfIgYAAgAh3hYQgJAAAAgNQAAgJAHgCIAzAAIAAgGQAAgIANgCQAOAAAAAKIAAAGIAuAAQAHACAAAKQAAAMgJAAg");
	this.shape_1.setTransform(11.9,14.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4,-3.8,66.3,66);


(lib.text5Up = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CC0000").s().p("Ah7B5IAAjoQACgRAVgBIBCAAQAXABAAAQIAABBQgCATgVAAIg9AAIAACTQAAALgOgBQgLABgDgJgAhfg3IAyAAQAHAAAAgGIAAgGIg5AAgAhfhhIAAAEIA5AAIAAgEQAAgFgFAAIgvAAQgFAAAAAFgAA8B6QgHAAgDgJIACgLQACgHAHgBQANAEALABQALAAAAgNIAAhyIhEAAQgTAAgBgXIAAg1QAAgTARgEIBNAAQAVAAABAVIAADEQAAAXgIAIQgCAIgaAAQgRgBgLgGgAAjg7QABAEAFAAIA3AAIAAgNIg9AAgAAjhhIAAAFIA9AAIAAgEQAAgGgFAAIgzAAQgFABAAAEgAhPBoQAAgGAIgHQAKgHAIgRQACgEABgGIgcAAQgJAAAAgOQAAgKAHgCIAgAAIAAgYIgZAAQgJAAAAgNQAAgKAHgCICWAAQAHABAAAMQAAAMgIAAIgdAAIAAAYIAkAAQAHABAAANQAAANgJgBIgiAAIAAAyQAAAKgNAAQgOgBAAgIIAAgzIgqAAQgGAlgYAVQgFAFgHAAQgLgCgCgOgAgWAfIAoAAIAAgYIgoAAg");
	this.shape.setTransform(40.1,15);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CC0000").s().p("Ah/B4IAAhfQAAgRARAAIAkAAIAEgKIgjAAQgQAAgBgRIAAg5QADgHAIAAQANAAAAAHIAAAtQAAAGAJAAIABAAQgEgEgBgGQAAgEACgCIAOgNIgJgHQgGgCAAgFQABgMAIgDIAEAAIASAOIAOgPQACgDADAAQANAEAAAKQAAAEgNAOIAKAIQAGAFAAAFQAAAIgEAEQAJgBAAgGIAAgsQAAgIAMAAQALAAAAAIIAAAbQAZghAKglQADgJAHAAQAPAAABAIQAAAHgCAGQgEALgEAKIAVAAQAHgQAGgUQADgEAGAAQAJABACAEQAEADAAAFQgEARgFAKIATAAQAIAAAAANQAAAOgJAAIgaAAIAAAfIAaAAQAIABAAAMQAAAOgJAAIgZAAIAAAiIAaAAQAIAAAAAMQAAAOgIAAIgaAAIAAAlIAZAAQAJAAAAAPQAAANgJAAIhVAAQgQAAgBgRIAAiGQgEACgEAAQgFAAgCgCIAAAIQAAAQgRABIgfAAIAAABIgCAJIAnAAQAQAAABARIAABKQAAAdgTAAQgQAAgPgEQgIAAgCgFQgCgDgBgHQABgHAHgDIAWAEQAHAAAAgGIAAgIIgHACQgGAAgDgFIgCgGQgVAJgYAEIgRAAIgCAAIAAAaQgCAKgLAAQgNAAgBgJgAAsBZQABAHAGAAIARAAIAAglIgYAAgAhkAjIAAAiIAHAAIAMglIgPAAQgBAAgBAAQAAAAgBABQAAAAgBABQAAAAAAABgAgeApQAFAFAHAUIAAgeQAAgEgFAAIggAAIgDAHIgIAZQALgCAKgDIgDgFQgBgCAAgFQAAgHAJgDQAIAAACAEgAAsAhIAYAAIAAgiIgYAAgAhLgZIAgAAIgPgOQgLAKgGAEgAAsgcIAYAAIAAgfIgYAAgAh3hYQgJAAAAgNQAAgJAHgCIAzAAIAAgGQAAgIANgCQAOAAAAAKIAAAGIAuAAQAHACAAAKQAAAMgJAAg");
	this.shape_1.setTransform(11.9,14.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4,-3.8,66.3,66);


(lib.shape40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#CCFFFF").ss(6,1,1).p("AUGpbMgoLAAAQgpAAgeASQgdASAAAaIAAQ7QAAAZAdATQAeASApAAMAoLAAAQApAAAdgSQAegTAAgZIAAw7QAAgagegSQgdgSgpAAg");
	this.shape.setTransform(0,-37.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6FB7FF").s().p("A0EJcQgqAAgdgSQgdgTAAgZIAAw7QAAgaAdgSQAdgSAqAAMAoJAAAQAqAAAdASQAdASAAAaIAAQ7QAAAZgdATQgdASgqAAg");
	this.shape_1.setTransform(0,-37.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-141.5,-100.5,283.1,126.8);


(lib.shape37UpOverDownHit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 5
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BB90FF").s().p("AjiECQgLAAgMgIQgLgIAAgMQAAgHAFgHQAlg+AYhrQADgRASAAQAhAAgBAVQAAAogeBUQggBTgXABIAAgBgAhVD2QgPgCAAgUQAAgcAXAAIC+ANIBFgEQAIgDAAgKQAAgHgHAAIkIAAQglABAAgiIAAghQAAgjAiABIEFAAQAJgBAAgJQAAgJgJABIkdAAQgRgBAAgVQAAgWAQAAIDiAAQgHgDAAgKIABgHIAMgyQACgMAMABQASgBAAARIgFAjQgGAbgGADIA/AAQAiAAAAAjIAAAhQAAAjglAAIkEAAQgIAAAAAIQAAAIAIAAIERAAQAiAAgCAtQABAkgVAPQgVARhxAAgAiiAOIARg8QACgKAKAAQATAAgBAOQABAJgJAfQgHAfgNABQgTAAAAgQgAhkAGQgBgagFgUIAAgEQAAgNASAAQAQAAADA7IAAADQABARgSAAQgOAAAAgQgACmAFQAAgZgEgVIgBgFQAAgNASAAQAWAAAAA/QAAARgVAAQgOAAAAgQgADgAIIgUgyIgDgIQABgPASAAQAJAAANAeIAPAjQgBAUgTAAQgLAAgCgMgAgxAFQgHgegJgUIgDgHQAAgOASAAQAJAAANAeQAMAhAAAFQAAAOgUAAQgLAAgCgLgAAOANQgcAAAAgcIAAghQAAgZAcAAIBFAAQAaAAAAAcIAAAfQAAAbgbAAgAAYgeQAAAMAIAAIAfAAQAHAAAAgMQAAgLgIAAIgeAAQgIAAAAALgAjJgQQgRgZgfgkQgFgIAAgHQAAgKAJgKQAJgJAKAAQALgBAeAlQAfAkABAKQAAAKgLALQgLAKgLAAQgKAAgFgIgADkhCIgDgJQhAANgsAAQgOAAAAgYIgGABIhkAAQgNgBAAgRQAAgPANAAIBkAAQAMAAAAAQIAIgCIAVgBIAOgSIglglQgHgGgBgHIgHABIhyAAQgMABAAgTQAAgSAMAAIByAAQAOAAAAARQAFgGAFAAQAGAAAHAHIAcg6QAEgJAIAAQAWAAAAARQAAAOgkA6IANAMIAbgvQAEgIAHAAQAXAAAAATQAAATg4BFIAjgFIgHgOIgCgHQAAgPARAAQAKAAAOAgQANAfAAAHQAAASgVAAQgIABgEgKgAgqhDIgDgJQhCAOgkAAQgQAAAAgUQAAgWAQABIAKAAIAFgBIAQgTIgjgjIgDgEQgJATgXgBQgMAAgHgLQgYgtgLgOQgFgGAAgHQAAgbAeAAQAZAAAlBIIABgCIAAgCQAGgJAGABQAHgBAHAHQANgUAPgnQAEgLAIABQAXAAAAAQQAAAUglA4IAIAKIAbgvQADgIAJAAQAXAAAAARQgBAYg7BCIAjgFIgHgNIgBgHQAAgQASAAQAJAAANAgQANAgAAAIQAAANgUABQgKgBgCgIgAgDiBQgNAAAAgRQAAgQANAAIBkAAQAMAAAAAQQAAARgMAAgAAAjaQgMAAAAgRQAAgPAMAAIBcAAQANAAAAAPQAAARgNAAg");
	this.shape.setTransform(109.4,32.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 4
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BB90FF").s().p("AheDpIADgRQhuAlgnAAQgUAAAAghQAAgVAPgBIA3gIIAAinIgwAAQgUAAAAgZQAAgbAUAAIAwAAIAAguIgdAAQgQAAAAgbIABgHIgDABQgIAAgHgLQgIgMAAgKQAAgNAHgFQAngfAfgzQAGgMARAAQAPAAAGAIQAXAjAdAbQAKALAAAKQAAAIgJALQgIAJgLAAQgPAAgigyQgBgCgEAAIgFACQgOAYgdAfIBeAAQATAAAAAaQAAAcgTAAIgaAAIAAAuIApAAQATAAAAAaQAAAagTAAIgpAAIAACaIAngNIAIgBQAGAAAFAEIADgWQACgQAQAAQAZAAAAASIgCAPQgLBOgEAHQgEAHgKAAQgcAAAAgVgABuD9QghAAAAgiIAAgFQgEAKgRAAQgOAAgDgVQgFgtgFgNIgBgGQAAgOAYAAQAHgBAEAFQAEAFAKA+IAAhUQgGAJgLAAQgOAAgFgQIgCgGQhWAUgaAAQgIgBgEgEQgGAngOAAQgcAAAAgSIAAgHQAMgwACghQABgQAOAAQAbABAAASIgBAEIAAAPIAOgBQAUgXAGgPQgRgZgmgpQgIgIAAgIQAAgIAKgJQAJgLAJAAQAHAAANAOIAXgoIgMAAQghgBAAgkIAAhGQAAgjAiAAID5AAQAlAAAAAjIAABKQAAAgggABIgHAAQAKAFAAALIgMAYIAjAAQASAAAAAaQAAAZgSAAIggAAIAAAkIAcAAQASAAAAAaQAAAYgSAAIgcAAIAAApIAcAAQASABAAAZQAAAYgSABIgcAAIAAAoIAjAAQATAAAAAYQAAAagTAAgAB9DAQAAALAKAAIAbAAIAAgoIglAAgAB9BwIAlAAIAAgpIglAAgABNBSIAAg7QgEAFgFAAQgJAAgJgIQgJgKAAgKQAAgIAGgGQAqgyAQgqIhnAAQAIAEAAALQAAANgiAtIAOARIAXgyQAFgLAKAAQAcAAAAAYQAAALgaAqIgqBBIAkgFIgGgNIgCgIQAAgSAYAAQAVAAAQA9gAB9gEIAAAZIAlAAIAAgkIgbAAQgKAAAAALgACShcQAAAJgLARIAUAAQANgVAIgTIgnAAQAJAEAAAKgACWicIAiAAQAKAAAAgOIAAgPQAAgOgMAAIggAAgAA7icIAsAAIAAgrIgsAAgAgZi6IAAARQAAANAMAAIAcAAIAAgrIgbAAQgNAAAAANgAgXDdIgBhLQAAgSAYAAQAOAAACAfIAEBBQAAASgUAAQgXgBAAgUgAj3CcQgDhGgGgeIgBgGQAAgUAcAAQARABAGAtIAHBOIAAADQAAAVgcABQgUAAAAgXg");
	this.shape_1.setTransform(54.2,32.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Layer 3
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#BB90FF").s().p("AglDwIAAm2IACgVQABgJAHgHQAGgGAJgEIATgCIDKAAIAUACQAJAEAFAGQAIAHABALIACAVIAAGPQAAAagMANQgLAMgWAAIhCgHQgYgIAAgSIADgNQACgHAGgFQAFgFAJAAIAcAIIATACQALAAAAgNIAAluIgDgMQgDgDgJAAIieAAQgIAAgDADQgEAEAAAIIAAGiQAAATgZAAQgaAAAAgTgAj0DzQgGgFgCgJIgBgPQAAgKAFgGQADgGAUgDIA2gLIAAifIg8AAQgJAAgGgHQgFgIAAgLQAAgbAUAAIA8AAIAAguIgjAAQgNAAgEgJIgDgSIABgHIgKgCIgMgKQgGgIAAgKIACgLIAOgOIAbgYIAXgcIAPgZQAIgMAOAAQAOAAALALIA3A1IAPAMQAKAJAAALQAAALgIAJQgJAKgLAAIgNgFIgUgQIggghIgFgDQgDAAgCAEIgVAcIgdAaIB4AAQAKAAAFAHQAFAGAAAOQAAAOgFAGQgFAHgKAAIgoAAIAAAuIAxAAQAUAAAAAbQAAAZgUAAIgxAAIAACSIAtgPIAIgBQAGAAAGAEQAGAEABAHIADAMQAAAHgEAGIgKAIIhiAfIhHAQIgFABQgHAAgGgEgAjqCbIgMhpQgBgJADgHQAEgHAIgBIANgBQAJAAAFAEQAEAGACAHIANBsQAAAJgFAFQgFAFgHACIgMABQgTAAAAgRgABFCiIgNgDQgFgCgIgIQgHgIAAgQIAAigQAAgSAKgJQAIgKAQAAIBMAAQAQAAAJAKQAJAJAAASIAACgQAAAQgJAKQgLALgOAAgABXgQIgDAFIAAAGIAABjQAAAJADACQABADAHAAIAaAAIAIgDIADgFIAAgGIAAhjIgDgKQgDgDgFAAIgaAAQgGAAgCACgAhiCMQgLgCAAgNIABgHIAMhPQABgJAEgDQAEgDAIAAIAGABQALABAEAFQAEAEABALIgMBVQgDAMgPAAgAAshoQgTAAAAgbQAAgbATAAIB/AAQAKAAAFAHQAFAHAAANQAAAbgUAAg");
	this.shape_2.setTransform(-1.6,33.2);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

	// Layer 2
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#D2A9FF").ss(10,1,1).p("Am6npIN1AAQATAAAOAOQAOAOAAATIAAN1QAAATgOAOQgOAOgTAAIt1AAQgTAAgOgOQgOgOAAgTIAAt1QAAgTAOgOQAOgOATAAg");
	this.shape_3.setTransform(-86.5,-10.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Am6HqQgTAAgOgOQgOgOAAgTIAAt1QAAgTAOgOQAOgOATAAIN1AAQATAAAOAOQAOAOAAATIAAN1QAAATgOAOQgOAOgTAAg");
	this.shape_4.setTransform(-86.5,-10.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3}]}).wait(1));

	// Layer 1
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#77A4E1").ss(10,1,1).p("Am6npIN1AAQATAAAOAOQAOAOAAATIAAN1QAAATgOAOQgOAOgTAAIt1AAQgTAAgOgOQgOgOAAgTIAAt1QAAgTAOgOQAOgOATAAg");
	this.shape_5.setTransform(-83.2,-5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#77A4E1").s().p("Am6HqQgTAAgOgOQgOgOAAgTIAAt1QAAgTAOgOQAOgOATAAIN1AAQATAAAOAOQAOAOAAATIAAN1QAAATgOAOQgOAOgTAAg");
	this.shape_6.setTransform(-83.2,-5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-140.5,-64.1,276,123.2);


(lib.shape33UpOverDownHit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF8600").s().p("AjlDvQgMgJAAgKQAAgJAHgIQA3g8AAhtIAAiOQgSAPgMAAQgfAAAAggQAAgNANgJQA+glAmgmQAZgaASAAIDmAAQAYAAAAAbQAAAag8A1IBmAAQAegBAAAeIgBE3QAAAvg1AAIhMgLQgugLAAgUQAAgmAcAAIBNASQAOAAAAgRIAAg5Ik0AAQgMA3gaArQgYApgUAAQgLABgNgKgAA6A1IB+AAIAAguIh+AAgAh6A1IB6AAIAAguIh6AAgAA6guIB+AAIAAgfQAAgMgPAAIhvAAgAh6hNIAAAfIB6AAIAAgrIhrAAQgPAAAAAMgAhgixIglAhIClAAQAzgpAAgIQAAgDgLAAIiDAAQgTAAgSATg");
	this.shape.setTransform(80,32.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF8600").s().p("AgpDyQgWAAAAgfQAAgdAWAAIBiAAIAAidIhVAAQgWAAAAgdQAAgeAWAAIBVAAIAAiTIhdAAQgWAAABgeQgBgeAWAAID8AAQAVAAAAAeQAAAegVAAIhiAAIAACTIBWAAQAVAAAAAeQAAAdgVAAIhWAAIAACdIBqAAQAVAAAAAdQAAAfgVAAgAjEDoQgxAAABgxIAAlsQgBgxAxAAIBOAAQAwAAAAAxIAAFsQAAAxgwAAgAi9CjQAAAOARAAIAeAAQARAAAAgOIAAiLIhAAAgAi9igIAACDIBAAAIAAiDQAAgPgRAAIgeAAQgRAAAAAPg");
	this.shape_1.setTransform(28.4,33);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Layer 2
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FF9A00").ss(10,1,1).p("AmxneINiAAQATAAAOANQANAOAAATIAANiQAAATgNANQgOANgTAAItiAAQgSAAgOgNQgNgNAAgTIAAtiQAAgTANgOQANgNATAAg");
	this.shape_2.setTransform(-56.2,-9.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AmwHfQgTAAgOgOQgNgNAAgSIAAtiQAAgTANgOQANgNAUAAINhAAQATAAAOANQANAOAAATIAANiQAAASgNANQgOAOgTAAg");
	this.shape_3.setTransform(-56.2,-9.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2}]}).wait(1));

	// Layer 1
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#77A4E1").ss(10,1,1).p("AHSnQQANANAAATIAANhQAAATgNAOQgNANgTAAItiAAQgTAAgOgNQgNgOAAgTIAAthQAAgTANgNQAOgOATAAINiAAQATAAANAOg");
	this.shape_4.setTransform(-53,-4.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#77A4E1").s().p("AmwHfQgTAAgNgNQgOgOAAgTIAAthQAAgTAOgNQANgOATAAINiAAQASAAANAOQAOANAAATIAANhQAAATgOAOQgNANgSAAg");
	this.shape_5.setTransform(-53,-4.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-109.1,-62.1,213.3,119.3);


(lib.shape29UpOverDownHit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#33CC33").s().p("Ai1DiQgpgBAAgoIAAlyQAAgoApABIFrAAQApgBAAAoIAAFyQAAAogpABgAAaCrICAAAQAMgBAAgPIAAiGIiMAAgAilCcQAAAOAOABIB6AAIAAiWIiIAAgAAaggICMAAIAAh9QAAgMgNAAIh/AAgAiliaIAAB6ICIAAIAAiJIh6AAQgOgBAAAQg");
	this.shape.setTransform(78.5,32.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#33CC33").s().p("AhxDXQAAgaAcAAQA4AAA9gZQA8gZAbg7QAag8AAhNIAAgbIgmhcIgCgHQABgYAeAAQAQAAAWA2QAYA7AWBAQAYBGAAAJQAAAXgbAAQgSAAgGgbIgHgbQgFBqhOA+QhOA9hwAAQgaAAAAgggAjmDnQgNgKAAgMQAAgHAFgGQAkgvAvhiQAIgSALAAQAKAAANAHQAMAJAAAKIgDAHIAAACQgVA0gjA9QgkA8gNAAQgIAAgNgKgAgZB2QghgIAAgUQAAghAZAAIAEABQAhAJARAAQAKAAAAgNIAAkaQABgSAaAAQAcAAgBAUIAAEtQABAzg8AAgAhtASIADgJQA0hyAHhRQACgVAUAAQAcAAAAAVQAAAxgcBaQgcBagZAAQgfAAAAgZgAiwgTIgmgeQgXgRAAgKQAAgKAIgKQAIgKAKAAQAKAAArAhQAqAgAAAOQAAALgJAJQgJAJgKAAQgHAAgZgVgAiQiLQgVgTgYgSQgSgOAAgLQAAgfAbAAQAKAAApAiIABAAQAqAkAAAOQAAAKgIAJQgKAKgKAAQgHAAgXgUg");
	this.shape_1.setTransform(26.6,30.4);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Layer 2
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#99FF66").ss(10,1,1).p("AminOINFAAQASAAANANQANANAAATIAANEQAAASgNANQgNANgSAAItFAAQgSAAgNgNQgNgNAAgSIAAtEQAAgTANgNQANgNASAAg");
	this.shape_2.setTransform(-54.4,-8.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AmiHPQgSAAgNgNQgNgNAAgSIAAtEQAAgTANgNQANgNASAAINFAAQASAAANANQANANAAATIAANEQAAASgNANQgNANgSAAg");
	this.shape_3.setTransform(-54.4,-8.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2}]}).wait(1));

	// Layer 1
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#77A4E1").ss(10,1,1).p("AminOINFAAQASAAANANQANANAAATIAANEQAAASgNANQgNANgSAAItFAAQgSAAgNgNQgNgNAAgSIAAtEQAAgTANgNQANgNASAAg");
	this.shape_4.setTransform(-51.3,-4.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#77A4E1").s().p("AmiHPQgSAAgNgNQgNgNAAgSIAAtEQAAgTANgNQANgNASAAINFAAQASAAANANQANANAAATIAANEQAAASgNANQgNANgSAAg");
	this.shape_5.setTransform(-51.3,-4.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-105.7,-60.2,206.4,115.4);


(lib.shape28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 7
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#CADEFF").ss(3,1,1).p("EgECAjsMAIFhHX");
	this.shape.setTransform(-367.8,-45.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 6
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#CADEFF").ss(4,1,1).p("EgAOAkQMAAdhIf");
	this.shape_1.setTransform(-4.4,-2);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Layer 5
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#CADEFF").ss(6,1,1).p("EA9NAEpMg4+AAAQANiiiFhXQhVg2hyADMg8JgHSQgXgDgSALQgSALgDASIgLBaQgCATAOAPQAPAPAYACMA9VAHYQA/AIAHhTQgOglA7A+QBGBLhBBfIAAB/QAAASAQANQAQAMAXAAMA6YAAAQAXAAAQgMQAQgNAAgSIAAhYQAAgSgQgNQgQgMgXAAg");
	this.shape_2.setTransform(-4,229.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#77A4E1").s().p("AC1HXQgXAAgQgMQgQgNAAgSIAAh/QBBhfhGhLQg7g+AOAlQgHBTg/gIMg9VgHYQgYgCgPgPQgOgPACgTIALhaQADgSASgLQASgLAXADMA8JAHSQBygDBVA2QCFBXgNCiMA4+AAAQAXAAAQAMQAQANAAASIAABYQAAASgQANQgQAMgXAAg");
	this.shape_3.setTransform(-4,229.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2}]}).wait(1));

	// Layer 4
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("EgfKgjsQgKiWEOAKMA1lgAUMAEsBKXMg5zAAKQkOgUgUCMUAAHhIVgAHgBkg");
	this.shape_4.setTransform(201.6,-7.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_4).wait(1));

	// Layer 3
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#FFFFFF").ss(6,1,1).p("AdYDVMg5YAAKIiWiqQhNgUBQizQAvhqBeApMA7CACHQhrBxAHCwg");
	this.shape_5.setTransform(196.4,231.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#EBEBEB").s().p("A+WA1QhNgUBQizQAvhqBeApMA7CACHQhrBxAHCwMg5YAAKg");
	this.shape_6.setTransform(196.4,231.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5}]}).wait(1));

	// Layer 2
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#CADEFF").ss(6,1,1).p("AizkoIAAJRIFnAAIg1pRg");
	this.shape_7.setTransform(375.5,241.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#A2CAFF").s().p("AizEpIAApRIExAAIA2JRg");
	this.shape_8.setTransform(375.5,241.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7}]}).wait(1));

	// Layer 1
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#CADEFF").ss(6,1,1).p("EAg+gjsMAAABN9Ihkj6IhkgUMg+zgH4MAIShHpQgKgyA8AAUAA8AAAA0BAGuQAohGDSA8g");
	this.shape_9.setTransform(-188.9,-6.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#A2CAFF").s().p("EAfaAmXIhkgUMg+zgH4MAIShHpQgKgyA8AAUAA8AAAA0BAGuQAohGDSA8MAAABN9g");
	this.shape_10.setTransform(-188.9,-6.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-404.1,-280,805.2,560);


(lib.shape24DownHit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#990000").ss(1,1,1).p("ADPjOIAAGdImdAAIAAmdg");
	this.shape.setTransform(-1.1,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF9999").s().p("AjODPIAAmdIGdAAIAAGdg");
	this.shape_1.setTransform(-1.1,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22.8,-21.7,43.4,43.4);


(lib.shape21UpOver = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#990000").ss(1,1,1).p("ADmDmInLAAIAAnLIHLAAg");
	this.shape.setTransform(-1.1,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF9999").s().p("AjlDmIAAnLIHLAAIAAHLg");
	this.shape_1.setTransform(-1.1,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-25.1,-24,48,48);


(lib.shape18DownHit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#003399").ss(1,1,1).p("ADPjOIAAGdImdAAIAAmdg");
	this.shape.setTransform(-1.1,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#99CCFF").s().p("AjODPIAAmdIGdAAIAAGdg");
	this.shape_1.setTransform(-1.1,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22.8,-21.7,43.4,43.4);


(lib.shape15UpOver = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#003399").ss(1,1,1).p("ADmDmInLAAIAAnLIHLAAg");
	this.shape.setTransform(-1.1,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#99CCFF").s().p("AjlDmIAAnLIHLAAIAAHLg");
	this.shape_1.setTransform(-1.1,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-25.1,-24,48,48);


(lib.shape12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#66FFFF").ss(6,1,1).p("AeTuNMg8lAAAQgqAAgdAdQgdAeAAApIAAZTQAAApAdAdQAdAeAqAAMA8lAAAQAqAAAdgeQAdgdAAgpIAA5TQAAgpgdgeQgdgdgqAAg");
	this.shape.setTransform(5.9,-12.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00CCFF").s().p("A+SOOQgqAAgdgeQgdgdAAgpIAA5TQAAgpAdgeQAdgdAqAAMA8lAAAQAqAAAdAdQAdAeAAApIAAZTQAAApgdAdQgdAegqAAg");
	this.shape_1.setTransform(5.9,-12.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-201,-106.1,413.9,188);


(lib.shape9UpOverDownHit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(4,1,1).p("Egu3gjJMBdvAAAMAAABGTMhdvAAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("Egu3AjKMAAAhGTMBdvAAAMAAABGTg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-302,-227,604,454);


(lib.shape6Over = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFCC99").ss(3,1,1).p("AGzDXItlAAIAAmtINlAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF9900").s().p("AmyDXIAAmtINlAAIAAGtg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-45,-23,90,46);


(lib.shape3Up = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFCC99").ss(3,1,1).p("AGzDXItlAAIAAmtINlAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF6600").s().p("AmyDXIAAmtINlAAIAAGtg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-45,-23,90,46);


(lib.shape2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 14
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#6D38BB").ss(2,1,1).p("A1bgtQGhhFIhCMQErA/CyADQC4ADEMg3QGahsH0AOQlKg8qABJIkAAbIi0AHIi8gPIkdgnQnihEm4BUgA2VgiIA6gL");
	this.shape.setTransform(-15.4,-135.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF9900").s().p("AAnBcQiygDkrg/QohiMmhBFQG4hUHiBEIEdAnIC9APICzgHIEAgbQKAhJFKA8Qn0gOmaBsQj+A0izAAIgTAAg");
	this.shape_1.setTransform(-12.5,-135.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer 13
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFF00").s().p("Ak1E5IAAm0QAAgRAOgMQANgMAOAAIDnAAIAAgsIkOAAQghAAAAgmQAAgnAhAAIEOAAIAAgbQAAgcAnAAQAnAAAAAbIAAAcIEKAAQAiAAAAAnQAAAmgiAAIkJAAIAAAsIDlAAQANAAANAMQAOAMAAARIAAGKQAAA4gqAAIg0ABIhFgEQgegDAAgjQAAgmAmAAIA8ADQAUAAAAgTIAAktQAAgTgSAAIhBAAQgLAtgUAqIBDAAQAhAAAAAjQAAAmghAAIiVAAIAAA0IB/AAQAhAAAAAlQAAAmghAAIh/AAIAABlQAAAcgmAAQgjAAAAgcIAAhlIiLAAQggAAAAgmQAAglAhAAICKAAIAAg0IiaAAQghAAAAgmQAAgjAhAAIBEAAQgVg+gQgZIg7AAQgSAAAAATIAAF+QAAAcgnAAQglAAAAgcgAgrgBIBXAAQAYgmAKgxIiYAAQAVA0AKAjg");
	this.shape_2.setTransform(94.6,-195.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

	// Layer 12
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFF00").s().p("Ak8EoQAAgpAfAAIAFABIAqAJQAMAAgBgYIAAiZQg4AcgOAAQglAAAAgxQAAgRAugTIA9gaIAAiQIhJAAQgdAAAAgkQAAglAdAAIBJAAIAAhhQAAgdAmAAQAnAAAAAdIAABhIAwAAQAdAAAAAlQAAAkgdAAIgwAAIAAByQArgaAMAAQANAAAKAOQAMAOAAANQAAAahaApIAADeQgBA8g8AAQhpAAAAgrgAAAFLQhBAAAAhCIAAjIQAAhBBBAAIEEAAQBBAAAABBIAADIQAABChBAAgAAKDyQgBATAWAAIDFAAQAVAAAAgTIAAgtIjvAAgAAKBYIAAAoIDvAAIAAgoQAAgTgVAAIjFAAQgWAAABATgAABglQhBAAgBg9IAAjTQABgdAlAAQAlAAAAAdIAAA7QCSgKBjgqIAVgFQAiAAAAAoQABAbhbAZQhZAYh5AKIAAAvQAAAaAbAAIDKAAQAOAAAFgJIABgCIADgMIAAgwQAAgeAlAAQAkAAAAAaIAABMQAABGhIAAg");
	this.shape_3.setTransform(22.1,-195.8);

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(1));

	// Layer 11
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFF00").s().p("AlQEoQAAgdAXgDIBBgIIAAlHQAAg5A7AAIFlAAQA7AAAAA5IAACcQAHgFAHAAQAPAAAOAPQANAQAAAOQAAAciGBGQBLAdBUAEQAgABAAAjQAAAuglABQhrAAh6g9Qh6g9hChbIg4AAIAAB5IBxgRIAHAAQAjAAAAAtQAAAOgJAIQgJAGh2ASIiZAUQggAAAAgtgABBC3QAYgKAcgQIA2gfIizAAQAeAkArAVgAiqA8IErAAQAVAAAAgRIAAgOIlAAAgAiqguIAAANIFAAAIAAgNQAAgQgVAAIkWAAQgVAAAAAQgACSioQgEASgWAAIjuAAQgWAAgFgSQh6A9giAAQgmAAAAgxQAAgXASgHQClg2BzhUQAVgQAUAAQAVAAAVAQQB0BUCkA2QASAHAAAXQAAAxgmAAQgiAAh6g9gAgJj8QgeAVgXAOIB9AAIg1gjQgFgEgFAAg");
	this.shape_4.setTransform(-49.4,-195.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_4).wait(1));

	// Layer 10
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFF00").s().p("AEqFVQg6AAhtg4Qhsg4gYgrQgyBChgAtQhfAsg7AAQgmAAAAgwQAAgbAhgDQCTgRBYhcIjqAAQgfAAAAgkQAAgkAgAAIECAAIADgqIj8AAQgeAAAAgkQAAgiAfAAID8AAIAAglIjYAAQgfAAAAgjQAAglAgAAIDXAAIAAghIj2AAQgeAAAAgkQAAgkAfAAICJAAIgjgkQgGgIAAgKQAAgpApAAQAfAABABfIBuAAQAVgXAdg2QALgTATAAQARAAAQALQAPALAAASQAAAJgfAvICHAAQAgAAAAAkQAAAkgeAAIkAAAIAAAhIDgAAQAhAAAAAlQAAAjgfAAIjiAAIAAAlIEFAAQAgAAAAAiQAAAkgeAAIkGAAIgBAqIEPAAQAhAAAAAkQAAAkgfAAIjyAAQBIA9CeAoQAuALAAAaQAAAxgpAAIgBAAg");
	this.shape_5.setTransform(-121.3,-195.4);

	this.timeline.addTween(cjs.Tween.get(this.shape_5).wait(1));

	// Layer 9
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#6D38BB").ss(6,1,1).p("AFVj2QAAAmgiAAIkJAAIAAAsIDlAAQANAAANAMQAOAMAAARIAAGKQAAA4gqAAIg0ABIhFgEQgegDAAgjQAAgmAmAAIA8ADQAUAAAAgTIAAktQAAgTgSAAIhBAAQgLAtgUAqIBDAAQAhAAAAAjQAAAmghAAIiVAAIAAA0IB/AAQAhAAAAAlQAAAmghAAIh/AAIAABlQAAAcgmAAQgjAAAAgcIAAhlIiLAAQggAAAAgmQAAglAhAAICKAAIAAg0IiaAAQghAAAAgmQAAgjAhAAIBEAAQgVg+gQgZIg7AAQgSAAAAATIAAF+QAAAcgnAAQglAAAAgcIAAm0QAAgRAOgMQANgMAOAAIDnAAIAAgsIkOAAQghAAAAgmQAAgnAhAAIEOAAIAAgbQAAgcAnAAQAnAAAAAbIAAAcIEKAAQAiAAAAAngABOhYIiYAAQAVA0AKAjIBXAAQAYgmAKgxg");
	this.shape_6.setTransform(94.6,-194.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_6).wait(1));

	// Layer 8
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#6D38BB").ss(6,1,1).p("AEGizQAAgeAlAAQAkAAAAAaIAABMQAABGhIAAIkGAAQhBAAAAg9IAAjTQAAgdAmAAQAkAAAAAdIAAA7QCSgKBjgqIAVgFQAjAAAAAoQAAAbhaAZQhaAYh5AKIAAAvQAAAaAbAAIDKAAQAOAAAGgJIAAgCIADgMgAksiLQgdAAAAgkQAAglAdAAIBKAAIAAhhQAAgdAlAAQAnAAAAAdIAABhIAwAAQAdAAAAAlQAAAkgdAAIgwAAIAAByQArgaAMAAQANAAALAOQALAOAAANQAAAahaApIAADeQAAA8g9AAQhpAAAAgrQAAgpAfAAIAFABIAqAJQAMAAAAgYIAAiZQg5AcgNAAQgmAAAAgxQAAgRAugTIA+gaIAAiQgADkBFIjEAAQgWAAAAATIAAAoIDwAAIAAgoQAAgTgWAAgAFFBBIAADIQAABChBAAIkEAAQhAAAAAhCIAAjIQAAhBBAAAIEEAAQBBAAAABBgAD6DyIAAgtIjwAAIAAAtQAAATAWAAIDEAAQAWAAAAgTg");
	this.shape_7.setTransform(22.1,-194.8);

	this.timeline.addTween(cjs.Tween.get(this.shape_7).wait(1));

	// Layer 7
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#6D38BB").ss(6,1,1).p("AAqlEQB0BUCkA2QASAHAAAXQAAAxgmAAQgiAAh6g9QgEASgWAAIjuAAQgWAAgFgSQh6A9giAAQgmAAAAgxQAAgXASgHQClg2BzhUQAVgQAUAAQAVAAAVAQgAiqghIFAAAIAAgNQAAgQgVAAIkWAAQgVAAAAAQgAi9iAIFlAAQA7AAAAA5IAACcQAHgFAHAAQAPAAAOAPQANAQAAAOQAAAciGBGQBLAdBUAEQAgABAAAjQAAAuglABQhrAAh6g9Qh6g9hChbIg4AAIAAB5IBxgRIAHAAQAjAAAAAtQAAAOgJAIQgJAGh2ASIiZAUQggAAAAgtQAAgdAXgDIBBgIIAAlHQAAg5A7AAgAg+jZIB9AAIg1gjQgFgEgFAAIgJAEQgeAVgXAOgAiqA8IErAAQAVAAAAgRIAAgOIlAAAgAB1CdIA2gfIizAAQAeAkArAVQAYgKAcgQg");
	this.shape_8.setTransform(-49.4,-194.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_8).wait(1));

	// Layer 6
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#6D38BB").ss(6,1,1).p("Ai/kqQAAgpApAAQAfAABABfIBuAAQAVgXAdg2QALgTATAAQARAAAQALQAPALAAASQAAAJgfAvICHAAQAgAAAAAkQAAAkgeAAIkAAAIAAAhIDgAAQAhAAAAAlQAAAjgfAAIjiAAIAAAlIEFAAQAgAAAAAiQAAAkgeAAIkGAAIgBAqIEPAAQAhAAAAAkQAAAkgfAAIjyAAQBIA9CeAoQAuALAAAaQAAAygqgBQg6AAhtg4Qhsg4gYgrQgyBChgAtQhfAsg7AAQgmAAAAgwQAAgbAhgDQCTgRBYhcIjqAAQgfAAAAgkQAAgkAgAAIECAAIADgqIj8AAQgeAAAAgkQAAgiAfAAID8AAIAAglIjYAAQgfAAAAgjQAAglAgAAIDXAAIAAghIj2AAQgeAAAAgkQAAgkAfAAICJAAIgjgkQgGgIAAgKg");
	this.shape_9.setTransform(-121.3,-194.4);

	this.timeline.addTween(cjs.Tween.get(this.shape_9).wait(1));

	// Layer 5
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#CADEFF").ss(6,1,1).p("AcTCbMg49AAAIAAkwMA6uAAAQAXAAARgNQAQgNAAgSIAAhcQAAgSgQgNQgRgNgXAAMg8HAAAQgXAAgRANQgQANAAASIAAI8QAAASAQANQAQAMAXAAMA6XAAAQAXAAAQgMQAQgNAAgSIAAhZQAAgRgQgNQgQgNgXAAg");
	this.shape_10.setTransform(0.1,237.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#77A4E1").s().p("A+EFKQgXAAgQgNQgQgMAAgSIAAo8QAAgSARgNQAQgNAXAAMA8HAAAQAXAAAQANQARANAAASIAABcQAAASgRANQgQANgXAAMg6uAAAIAAEwMA49AAAQAXAAAQANQAQANAAARIAABZQAAASgQAMQgQANgXAAg");
	this.shape_11.setTransform(0.1,237.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10}]}).wait(1));

	// Layer 4
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#FFFFFF").ss(6,1,1).p("Ab7DNMg5ZAAAIAAmZMA69AAUQhrBxAHEUg");
	this.shape_12.setTransform(-0.8,236.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#EBEBEB").s().p("A9eDNIAAmZMA69AAUQhrByAHETg");
	this.shape_13.setTransform(-0.8,236.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12}]}).wait(1));

	// Layer 3
	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#CADEFF").ss(6,1,1).p("AizkoIAAJRIFnAAIg1pRg");
	this.shape_14.setTransform(168.9,234.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#A2CAFF").s().p("AizEpIAApRIExAAIA2JRg");
	this.shape_15.setTransform(168.9,234.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14}]}).wait(1));

	// Layer 2
	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#6D38BB").ss(2,1,1).p("A1bgtQGhhFIhCMQErA/CyADQC4ADEMg3QGahsH0AOQltgcpdApIkBATIizAIIi8gLIkdgkQnihEm4BUgA2VgiIA6gL");
	this.shape_16.setTransform(-15.4,-133.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6D38BB").s().p("AAnBcQiygDkrg/QohiMmhBFQG4hUHiBEIEdAkIC9ALICygIIEBgTQJdgpFtAcQn0gOmaBsQj/A0iyAAIgTAAg");
	this.shape_17.setTransform(-12.5,-133.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16}]}).wait(1));

	// Layer 1
	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#CADEFF").ss(6,1,1).p("EAaTgksMAEpBKIMg93AAAMAAAhJ5QgFgXAYgXQAKgKAXgEMA3gAAAQAbgGARANQAQANgCAZg");
	this.shape_18.setTransform(0,-30.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#A2CAFF").s().p("Ege7AlcMAAAhJ5QgFgXAYgXQAKgKAXgEMA3gAAAQAbgGARANQAQANgCAZMAEpBKIg");
	this.shape_19.setTransform(0,-30.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-201,-273.1,402.1,546.2);


(lib.shape1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BAD264").s().p("Egu3AjKMAAAhGTMBdvAAAMAAABGTg");
	this.shape.setTransform(300,225);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,600,450);


(lib.button39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 6
	this.instance = new lib.text38UpOverDownHit("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-116.5,-103.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1));

	// Layer 5
	this.instance_1 = new lib.shape37UpOverDownHit("synched",0);
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-140.5,-106.9,276,290.3);


(lib.button36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_2 = function() {
		playSound("sound35overtodown");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(2).call(this.frame_2).wait(2));

	// Layer 5
	this.instance = new lib.text34UpOverDownHit("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-93,-99.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1));

	// Layer 4
	this.instance_1 = new lib.shape33UpOverDownHit("synched",0);
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-109.1,-103.3,213.3,322.2);


(lib.button32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 5
	this.instance = new lib.text31UpOverDownHit("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-80.6,-99.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1));

	// Layer 4
	this.instance_1 = new lib.shape29UpOverDownHit("synched",0);
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-105.7,-103.3,206.4,322.2);


(lib.button26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.text22Up("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-19.1,-17);

	this.instance_1 = new lib.text23Over("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(-19.1,-17);

	this.instance_2 = new lib.text25DownHit("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(-17.1,-16);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).wait(1));

	// Layer 1
	this.instance_3 = new lib.shape21UpOver("synched",0);
	this.instance_3.parent = this;

	this.instance_4 = new lib.shape24DownHit("synched",0);
	this.instance_4.parent = this;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3}]}).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-25.1,-24,48,87);


(lib.button20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.text16Up("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-19.1,-18);

	this.instance_1 = new lib.text17Over("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(-19.1,-18);

	this.instance_2 = new lib.text19DownHit("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(-16.1,-15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).wait(1));

	// Layer 1
	this.instance_3 = new lib.shape15UpOver("synched",0);
	this.instance_3.parent = this;

	this.instance_4 = new lib.shape18DownHit("synched",0);
	this.instance_4.parent = this;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3}]}).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-25.1,-24,48,86);


(lib.button10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.shape9UpOverDownHit("synched",0);
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-302,-227,604,454);


(lib.button8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.instance = new lib.text7Over("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-28,-13.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).to({_off:true},1).wait(2));

	// Layer 2
	this.instance_1 = new lib.text5Up("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(-28,-13.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({x:-27,y:-12.6},0).wait(1).to({startPosition:0},0).wait(1).to({startPosition:0},0).wait(1));

	// Layer 1
	this.instance_2 = new lib.shape3Up("synched",0);
	this.instance_2.parent = this;

	this.instance_3 = new lib.shape6Over("synched",0);
	this.instance_3.parent = this;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2}]}).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-45,-23,90,71.6);


(lib.sprite27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		/* 在此帧处停止
		时间轴将在插入此代码的帧处停止/暂停。
		也可用于停止/暂停影片剪辑的时间轴。
		*/
		
		this.stop();
		/* stop ();
		*/
	}
	this.frame_1 = function() {
		/* play ();
		*/
	}
	this.frame_2 = function() {
		playSound("sound11");
	}
	this.frame_7 = function() {
		/* 在此帧处停止
		时间轴将在插入此代码的帧处停止/暂停。
		也可用于停止/暂停影片剪辑的时间轴。
		*/
		
		this.stop();
		
		/* Mouse Click 事件
		单击此指定的元件实例会执行您可在其中添加自己的自定义代码的函数。
		
		说明:
		1. 在以下"// 开始您的自定义代码"行后的新行上添加您的自定义代码。
		单击此元件实例时，此代码将执行。
		*/
		
		this.trueButton.addEventListener("click", fl_MouseClickHandler.bind(this));
		
		function fl_MouseClickHandler()
		{
			window.close();
		}
		
		/* 单击以转到帧并停止
		单击指定的元件实例会将播放头移动到时间轴中的指定帧并停止影片。
		可在主时间轴或影片剪辑时间轴上使用。
		
		说明:
		1. 单击元件实例时，用希望播放头移动到的帧编号替换以下代码中的数字 5。
		2. EaselJS 中的帧编号从 0 开始而不是从 1 开始
		*/
		
		
		this.falsebutton.addEventListener("click", fl_ClickToGoToAndStopAtFrame.bind(this));
		
		function fl_ClickToGoToAndStopAtFrame()
		{
			this.gotoAndStop(0);
		}
		/* stop ();
		*/
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1).call(this.frame_2).wait(5).call(this.frame_7).wait(1));

	// Layer 8
	this.falsebutton = new lib.button26();
	this.falsebutton.name = "falsebutton";
	this.falsebutton.parent = this;
	this.falsebutton.setTransform(165.9,-16);
	this.falsebutton._off = true;
	new cjs.ButtonHelper(this.falsebutton, 0, 1, 2, false, new lib.button26(), 3);

	this.timeline.addTween(cjs.Tween.get(this.falsebutton).wait(7).to({_off:false},0).wait(1));

	// Layer 5
	this.trueButton = new lib.button20();
	this.trueButton.name = "trueButton";
	this.trueButton.parent = this;
	this.trueButton.setTransform(106.1,-16);
	this.trueButton._off = true;
	new cjs.ButtonHelper(this.trueButton, 0, 1, 2, false, new lib.button20(), 3);

	this.timeline.addTween(cjs.Tween.get(this.trueButton).wait(7).to({_off:false},0).wait(1));

	// Layer 4
	this.instance = new lib.text14("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-176,-30.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(7).to({_off:false},0).wait(1));

	// Layer 3
	this.instance_1 = new lib.shape12("synched",0);
	this.instance_1.parent = this;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(7).to({_off:false},0).wait(1));

	// Layer 1
	this.instance_2 = new lib.button10();
	this.instance_2.parent = this;
	this.instance_2.setTransform(255,-190.7,0.15,0.15);
	this.instance_2.alpha = 0.398;
	this.instance_2._off = true;
	new cjs.ButtonHelper(this.instance_2, 0, 1, 2, false, new lib.button10(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({_off:false},0).to({scaleX:0.79,scaleY:0.79,x:63.7,y:-47.6},3).wait(1).to({scaleX:1,scaleY:1,x:0,y:0},0).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


// stage content:
(lib.Book = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{Shatin:25,Mongkok:35,Causewaybay:45});

	// timeline functions:
	this.frame_0 = function() {
		/* Mouse Click 事件
		单击此指定的元件实例会执行您可在其中添加自己的自定义代码的函数。
		
		说明:
		1. 在以下"// 开始您的自定义代码"行后的新行上添加您的自定义代码。
		单击此元件实例时，此代码将执行。
		*/
		
		this.exitButton.addEventListener("click", fl_MouseClickHandler_6.bind(this));
		
		function fl_MouseClickHandler_6()
		{
			/* 播放影片剪辑
		播放舞台上指定的影片剪辑。
		
		说明:
		1. 将此代码用于当前停止的影片剪辑。
		*/
		console.log("沙田")
		this.Quit.play();
		
			
		}
		/* fscommand("fullscreen", "true");
		fscommand("allowscale", "true");
		fscommand("trapallkeys", "false");
		play ();
		*/
	}
	this.frame_22 = function() {
		/* Mouse Click 事件
		单击此指定的元件实例会执行您可在其中添加自己的自定义代码的函数。
		
		说明:
		1. 在以下"// 开始您的自定义代码"行后的新行上添加您的自定义代码。
		单击此元件实例时，此代码将执行。
		*/
		
		this.shatianButton.addEventListener("click", fl_MouseClickHandler_3.bind(this));
		
		function fl_MouseClickHandler_3()
		{
			continueFourGame();
		}
		
		/* Mouse Click 事件
		单击此指定的元件实例会执行您可在其中添加自己的自定义代码的函数。
		
		说明:
		1. 在以下"// 开始您的自定义代码"行后的新行上添加您的自定义代码。
		单击此元件实例时，此代码将执行。
		*/
		
		this.wangjiaoButton.addEventListener("click", fl_MouseClickHandler_4.bind(this));
		
		function fl_MouseClickHandler_4()
		{
			continueThirteenGame();
			console.log("2")
		}
		
		/* Mouse Click 事件
		单击此指定的元件实例会执行您可在其中添加自己的自定义代码的函数。
		
		说明:
		1. 在以下"// 开始您的自定义代码"行后的新行上添加您的自定义代码。
		单击此元件实例时，此代码将执行。
		*/
		
		this.tongluowanButton.addEventListener("click", fl_MouseClickHandler_5.bind(this));
		
		function fl_MouseClickHandler_5()
		{
			continueTwentyFourGame();
			console.log("3")
		}
		/* stop ();
		*/
	}
	this.frame_25 = function() {
		/* play ();
		*/
	}
	this.frame_32 = function() {
		/* stop ();
		loadMovieNum("Shatin.swf", 0);
		*/
	}
	this.frame_35 = function() {
		/* play ();
		*/
	}
	this.frame_43 = function() {
		/* stop ();
		loadMovieNum("Mongkok.swf", 0);
		*/
	}
	this.frame_45 = function() {
		/* play ();
		*/
	}
	this.frame_53 = function() {
		/* 在此帧处停止
		时间轴将在插入此代码的帧处停止/暂停。
		也可用于停止/暂停影片剪辑的时间轴。
		*/
		
		this.stop();
		/* stop ();
		loadMovieNum("CWB.swf", 0);
		*/
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(22).call(this.frame_22).wait(3).call(this.frame_25).wait(7).call(this.frame_32).wait(3).call(this.frame_35).wait(8).call(this.frame_43).wait(2).call(this.frame_45).wait(8).call(this.frame_53).wait(2));

	// Layer 34
	this.Quit = new lib.sprite27();
	this.Quit.name = "Quit";
	this.Quit.parent = this;
	this.Quit.setTransform(960,720.2,3.2,3.2);

	this.timeline.addTween(cjs.Tween.get(this.Quit).wait(55));

	// Layer 30
	this.exitButton = new lib.button8();
	this.exitButton.name = "exitButton";
	this.exitButton.parent = this;
	this.exitButton.setTransform(1825.1,53.1,1.984,1.984);
	new cjs.ButtonHelper(this.exitButton, 0, 1, 2, false, new lib.button8(), 3);

	this.timeline.addTween(cjs.Tween.get(this.exitButton).wait(55));

	// Layer 29
	this.instance = new lib.text41("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(370.1,524.8,1.156,1.156);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(18).to({_off:false},0).to({scaleX:2.52,scaleY:2.52,x:224.2,y:488.8},2).wait(1).to({scaleX:3.2,scaleY:3.2,x:151.2,y:470.6},0).to({startPosition:0},4).to({scaleX:1.16,scaleY:1.16,x:370.1,y:524.8},4).to({_off:true},1).wait(5).to({_off:false,scaleX:3.2,scaleY:3.2,x:151.2,y:470.6},0).to({scaleX:1.16,scaleY:1.16,x:370.1,y:524.8},4).to({_off:true},1).wait(5).to({_off:false,scaleX:3.2,scaleY:3.2,x:151.2,y:470.6},0).to({scaleX:1.16,scaleY:1.16,x:370.1,y:524.8},4).to({_off:true},1).wait(5));

	// Layer 28
	this.instance_1 = new lib.shape40("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(493.8,598.2,1.156,1.156);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(18).to({_off:false},0).to({scaleX:2.52,scaleY:2.52,y:649},2).wait(1).to({scaleX:3.2,scaleY:3.2,y:674.1},0).to({startPosition:0},4).to({scaleX:1.16,scaleY:1.16,y:598.2},4).to({_off:true},1).wait(5).to({_off:false,scaleX:3.2,scaleY:3.2,y:674.1},0).to({scaleX:1.16,scaleY:1.16,y:598.2},4).to({_off:true},1).wait(5).to({_off:false,scaleX:3.2,scaleY:3.2,y:674.1},0).to({scaleX:1.16,scaleY:1.16,y:598.2},4).to({_off:true},1).wait(5));

	// Layer 21
	this.tongluowanButton = new lib.button39();
	this.tongluowanButton.name = "tongluowanButton";
	this.tongluowanButton.parent = this;
	this.tongluowanButton.setTransform(1373.3,1076.5,2.24,2.24);
	this.tongluowanButton._off = true;
	new cjs.ButtonHelper(this.tongluowanButton, 0, 1, 2, false, new lib.button39(), 3);

	this.timeline.addTween(cjs.Tween.get(this.tongluowanButton).wait(12).to({_off:false},0).wait(43));

	// Layer 15
	this.instance_2 = new lib.shape2("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(1451.5,773.6,2.24,2.24);

	this.wangjiaoButton = new lib.button36();
	this.wangjiaoButton.name = "wangjiaoButton";
	this.wangjiaoButton.parent = this;
	this.wangjiaoButton.setTransform(1576.2,725.6,2.24,2.24);
	new cjs.ButtonHelper(this.wangjiaoButton, 0, 1, 2, false, new lib.button36(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2}]}).to({state:[{t:this.wangjiaoButton}]},12).wait(43));

	// Layer 9
	this.shatianButton = new lib.button32();
	this.shatianButton.name = "shatianButton";
	this.shatianButton.parent = this;
	this.shatianButton.setTransform(1302.2,370.4,2.24,2.24);
	this.shatianButton._off = true;
	new cjs.ButtonHelper(this.shatianButton, 0, 1, 2, false, new lib.button32(), 3);

	this.timeline.addTween(cjs.Tween.get(this.shatianButton).wait(12).to({_off:false},0).wait(43));

	// Layer 8
	this.instance_3 = new lib.shape28("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(988.8,758.4,2.24,2.24);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(12).to({_off:false},0).wait(43));

	// Layer 1
	this.instance_4 = new lib.shape1("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,0,3.2,3.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(55));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(960,720,1920,1440);
// library properties:
lib.properties = {
	id: 'D3E5BBB9508CBC42A2F44A2251C1834B',
	width: 1920,
	height: 1440,
	fps: 12,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"sounds/sound11.mp3", id:"sound11"},
		{src:"sounds/sound35overtodown.mp3", id:"sound35overtodown"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['D3E5BBB9508CBC42A2F44A2251C1834B'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;